#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_MonsterBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PhysicsCore_structs.hpp"
#include "Pal_structs.hpp"
#include "Pal_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "ABP_MonsterBase_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_MonsterBase.ABP_MonsterBase_C
// 0x1F20 (0x2540 - 0x0620)
class UABP_MonsterBase_C : public UPalAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0620(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct ABP_MonsterBase::FAnimBlueprintGeneratedMutableData __AnimBlueprintMutables;                           // 0x0628(0x0060)(HasGetValueTypeHash)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x0688(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x0690(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root_4;                              // 0x0698(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_4;                   // 0x06B8(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_3;                              // 0x0780(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_3;                   // 0x07A0(0x00C8)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_2;                   // 0x0868(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_2;                              // 0x0930(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_1;                   // 0x0950(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_1;                              // 0x0A18(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x0A38(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0B00(0x0020)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_11;                 // 0x0B20(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_10;                 // 0x0B48(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_9;                  // 0x0B70(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_8;                  // 0x0B98(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_7;                  // 0x0BC0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_6;                  // 0x0BE8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_5;                  // 0x0C10(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_4;                  // 0x0C38(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3;                  // 0x0C60(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2;                  // 0x0C88(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0x0CB0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x0CD8(0x0028)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer_3;                   // 0x0D00(0x00C8)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_7;                  // 0x0DC8(0x0070)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_4;                       // 0x0E38(0x0020)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_6;                  // 0x0E58(0x0070)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_7;                   // 0x0EC8(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2;                    // 0x0F10(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_3;                       // 0x0F58(0x0020)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_5;                  // 0x0F78(0x0070)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_6;                   // 0x0FE8(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x1030(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2;                       // 0x1078(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x1098(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x10E0(0x0020)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_5;                   // 0x1100(0x0048)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_4;                  // 0x1148(0x0070)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_4;                   // 0x11B8(0x0048)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_3;                   // 0x1200(0x0048)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_3;                  // 0x1248(0x0070)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_2;                  // 0x12B8(0x0070)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_2;                   // 0x1328(0x0048)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_1;                  // 0x1370(0x0070)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer;                    // 0x13E0(0x0070)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x1450(0x0020)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x1470(0x00C8)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_1;                              // 0x1538(0x0048)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x1580(0x0048)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer_2;                   // 0x15C8(0x00C8)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_3;                    // 0x1690(0x0108)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_7;                     // 0x1798(0x0028)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_1;                   // 0x17C0(0x0048)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_6;                     // 0x1808(0x0028)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_2;                    // 0x1830(0x0108)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_5;                     // 0x1938(0x0028)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool;                     // 0x1960(0x0048)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_4;                     // 0x19A8(0x0028)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer_1;                   // 0x19D0(0x00C8)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_1;                    // 0x1A98(0x0108)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_3;                     // 0x1BA0(0x0028)()
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend;                         // 0x1BC8(0x00C8)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_2;                     // 0x1C90(0x0028)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer;                     // 0x1CB8(0x00C8)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x1D80(0x0108)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1;                     // 0x1E88(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x1EB0(0x0028)()
	class UPalCharacterMovementComponent*         K2Node_PropertyAccess_17;                          // 0x1ED8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_PropertyAccess_15;                          // 0x1EE0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5321[0x7];                                     // 0x1EE1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalCharacterMovementComponent*         K2Node_PropertyAccess_14;                          // 0x1EE8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_PropertyAccess_12;                          // 0x1EF0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5322[0x3];                                     // 0x1EF1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_PropertyAccess_10;                          // 0x1EF4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_PropertyAccess_9;                           // 0x1EF8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5323[0x4];                                     // 0x1EFC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                K2Node_PropertyAccess_8;                           // 0x1F00(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_PropertyAccess_7;                           // 0x1F18(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5324[0x7];                                     // 0x1F19(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FWeaponAnimationInfo                   K2Node_PropertyAccess_6;                           // 0x1F20(0x0260)()
	struct FVector                                K2Node_PropertyAccess_5;                           // 0x2180(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_PropertyAccess_3;                           // 0x2198(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               K2Node_PropertyAccess_2;                           // 0x21B0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_PropertyAccess_1;                           // 0x21C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_PropertyAccess;                             // 0x21C9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5325[0x6];                                     // 0x21CA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               __CustomProperty_AimRotator_D409488B47D1A68373AC2E9D883DDF47; // 0x21D0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                __CustomProperty_LookAtWorldLocation_FBA1F7A649A7D6231954198C8C515A62; // 0x21E8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsAiming;                                          // 0x2200(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsShooting;                                        // 0x2201(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5326[0x6];                                     // 0x2202(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FWeaponAnimationInfo                   WeaponAnimInfo;                                    // 0x2208(0x0260)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FVector2D                              CameraVelocityXY;                                  // 0x2468(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               AimRotator;                                        // 0x2478(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          IsLookatEnable;                                    // 0x2490(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5327[0x7];                                     // 0x2491(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                LookAtTarget;                                      // 0x2498(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        LookatInTime;                                      // 0x24B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        LookatOutTime;                                     // 0x24B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsJumpPreliminary;                                 // 0x24C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsSkipJumpStart;                                   // 0x24C1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5328[0x6];                                     // 0x24C2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        AngleSpeed;                                        // 0x24C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsRiding;                                          // 0x24D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsFlying;                                          // 0x24D1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ShouldBeUseShooterComponent;                       // 0x24D2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ShouldBeUseRiderComponent;                         // 0x24D3(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5329[0x4];                                     // 0x24D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        PrevMoveSpeed;                                     // 0x24D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UNiagaraSystem*                         FootStepEffectClass;                               // 0x24E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class FName                                   FootStepAttachPointName;                           // 0x24E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      FootStepEffect;                                    // 0x24F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          TSCached_OwnerPalCharacter;                        // 0x24F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UPalShooterComponent*                   TSCached_ShooterComponent;                         // 0x2500(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPalLookAtComponent*                    TSCached_LookAtComponent;                          // 0x2508(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPalRideMarkerComponent*                TSCached_RideMarker;                               // 0x2510(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          IsSpawnDashEffect;                                 // 0x2518(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_532A[0x7];                                     // 0x2519(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        DashEffectSpeed;                                   // 0x2520(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsFloating;                                        // 0x2528(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_532B[0x7];                                     // 0x2529(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        MovementScale;                                     // 0x2530(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AimingOverride(const struct FPoseLink& DefaultPose, const struct FRotator& Param_AimRotator, struct FPoseLink* Param_AimingOverride);
	void AnimGraph(struct FPoseLink* Param_AnimGraph);
	void AnimNotify_Landing();
	void BlueprintBeginPlay();
	void BlueprintPostEvaluateAnimation();
	void BlueprintThreadSafeUpdateAnimation(float DeltaTime);
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void CanSpawnFootStepEffect(bool* CanSpawn);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendListByBool_B62C4ED042628BD16274AFA4FDD16719();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendListByBool_C95153CD4007A62F8D752891550DF5D9();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendListByBool_FB442B974C195CB35B6129B622134627();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendSpacePlayer_40ADA346423143A5CAA0D4B50B157F15();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendSpacePlayer_672678E246E619FB275DE5AFE6DDA234();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendSpacePlayer_6FEC962E4C28F1AC8D56A49C89C4ADFA();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendSpacePlayer_925DF20E402882570857548CCD9E3C68();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendSpacePlayer_ADBAEE7E4B8D4BFED7B43DBC07178B76();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendSpacePlayer_E84338B149C6CA71A04CD2A2AFEE1A26();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_BlendSpacePlayer_ECFECB414886E0974195E991463ACD99();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_SequencePlayer_128A52BB436E9B3A31FBB7A0A5CC15C1();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_SequencePlayer_EA0B5CD54E5A85E50831B98555463D29();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_SequencePlayer_FE682B1C41C3E7BF960F52B352036D22();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_12D0A21548EC4F9A1B3A7F89B42E002E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_56B64F4E4C9E82DE226407ACE61B8F62();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_6D5D23194B5DCCF74E79899BDAC0B9BA();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_8E5298E14CFFC43AC4CB97899CB66188();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_94EBA2794624A1AE0E87B0B8F0C035CA();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_A47488D6499D3064732F10A46F49E205();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_CE52F1054119833750D5A6BE24F3D0CF();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_EE0E56854535C9DCA7F729A194F159F1();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_F0D464AD4B31CE2D2A7A7EA95C239B70();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_F48506EF4272DE0D9403FC8091658CC2();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MonsterBase_AnimGraphNode_TransitionResult_F96787034784DF12FF90028A34BB8B39();
	void ExecuteUbergraph_ABP_MonsterBase(int32 EntryPoint);
	void GetFootStepCharacterSpeed(double* CharacterSpeed);
	void GetFootStepEffectScale(double* Scale);
	void GetSprint(bool* IsSprint);
	void IsFloatingPal();
	void LookAtOverride(const struct FPoseLink& InPose, const struct FVector& LookAtWorldLocation, struct FPoseLink* Param_LookAtOverride);
	void MakeSwitchStatePalSize(class APalMonsterCharacter* Pal, class FString* PalSize);
	void MonsterPhysics(const struct FPoseLink& InPose, struct FPoseLink* Param_MonsterPhysics);
	void PlayLandingSound();
	void PlaySound(class FName SoundId);
	void PostUpdateDashEffect();
	void StartFootStepEffect();
	void StopFootStepEffect();
	void Update_Look_at_Parameter();
	void UpdateBasicParameter();
	void UpdateDashEffect_AnyThread();
	void UpdateRidingParameter();
	void UpdateShooterParameter();
	void UpperOverride(const struct FPoseLink& NativePose, const struct FPoseLink& ActionPose, struct FPoseLink* Param_UpperOverride);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_MonsterBase_C">();
	}
	static class UABP_MonsterBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_MonsterBase_C>();
	}
};
static_assert(alignof(UABP_MonsterBase_C) == 0x000010, "Wrong alignment on UABP_MonsterBase_C");
static_assert(sizeof(UABP_MonsterBase_C) == 0x002540, "Wrong size on UABP_MonsterBase_C");
static_assert(offsetof(UABP_MonsterBase_C, UberGraphFrame) == 0x000620, "Member 'UABP_MonsterBase_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, __AnimBlueprintMutables) == 0x000628, "Member 'UABP_MonsterBase_C::__AnimBlueprintMutables' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimBlueprintExtension_PropertyAccess) == 0x000688, "Member 'UABP_MonsterBase_C::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimBlueprintExtension_Base) == 0x000690, "Member 'UABP_MonsterBase_C::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_Root_4) == 0x000698, "Member 'UABP_MonsterBase_C::AnimGraphNode_Root_4' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_LinkedInputPose_4) == 0x0006B8, "Member 'UABP_MonsterBase_C::AnimGraphNode_LinkedInputPose_4' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_Root_3) == 0x000780, "Member 'UABP_MonsterBase_C::AnimGraphNode_Root_3' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_LinkedInputPose_3) == 0x0007A0, "Member 'UABP_MonsterBase_C::AnimGraphNode_LinkedInputPose_3' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_LinkedInputPose_2) == 0x000868, "Member 'UABP_MonsterBase_C::AnimGraphNode_LinkedInputPose_2' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_Root_2) == 0x000930, "Member 'UABP_MonsterBase_C::AnimGraphNode_Root_2' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_LinkedInputPose_1) == 0x000950, "Member 'UABP_MonsterBase_C::AnimGraphNode_LinkedInputPose_1' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_Root_1) == 0x000A18, "Member 'UABP_MonsterBase_C::AnimGraphNode_Root_1' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_LinkedInputPose) == 0x000A38, "Member 'UABP_MonsterBase_C::AnimGraphNode_LinkedInputPose' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_Root) == 0x000B00, "Member 'UABP_MonsterBase_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_TransitionResult_11) == 0x000B20, "Member 'UABP_MonsterBase_C::AnimGraphNode_TransitionResult_11' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_TransitionResult_10) == 0x000B48, "Member 'UABP_MonsterBase_C::AnimGraphNode_TransitionResult_10' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_TransitionResult_9) == 0x000B70, "Member 'UABP_MonsterBase_C::AnimGraphNode_TransitionResult_9' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_TransitionResult_8) == 0x000B98, "Member 'UABP_MonsterBase_C::AnimGraphNode_TransitionResult_8' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_TransitionResult_7) == 0x000BC0, "Member 'UABP_MonsterBase_C::AnimGraphNode_TransitionResult_7' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_TransitionResult_6) == 0x000BE8, "Member 'UABP_MonsterBase_C::AnimGraphNode_TransitionResult_6' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_TransitionResult_5) == 0x000C10, "Member 'UABP_MonsterBase_C::AnimGraphNode_TransitionResult_5' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_TransitionResult_4) == 0x000C38, "Member 'UABP_MonsterBase_C::AnimGraphNode_TransitionResult_4' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_TransitionResult_3) == 0x000C60, "Member 'UABP_MonsterBase_C::AnimGraphNode_TransitionResult_3' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_TransitionResult_2) == 0x000C88, "Member 'UABP_MonsterBase_C::AnimGraphNode_TransitionResult_2' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_TransitionResult_1) == 0x000CB0, "Member 'UABP_MonsterBase_C::AnimGraphNode_TransitionResult_1' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_TransitionResult) == 0x000CD8, "Member 'UABP_MonsterBase_C::AnimGraphNode_TransitionResult' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_LinkedAnimLayer_3) == 0x000D00, "Member 'UABP_MonsterBase_C::AnimGraphNode_LinkedAnimLayer_3' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_BlendSpacePlayer_7) == 0x000DC8, "Member 'UABP_MonsterBase_C::AnimGraphNode_BlendSpacePlayer_7' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_StateResult_4) == 0x000E38, "Member 'UABP_MonsterBase_C::AnimGraphNode_StateResult_4' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_BlendSpacePlayer_6) == 0x000E58, "Member 'UABP_MonsterBase_C::AnimGraphNode_BlendSpacePlayer_6' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_BlendListByBool_7) == 0x000EC8, "Member 'UABP_MonsterBase_C::AnimGraphNode_BlendListByBool_7' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_SequencePlayer_2) == 0x000F10, "Member 'UABP_MonsterBase_C::AnimGraphNode_SequencePlayer_2' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_StateResult_3) == 0x000F58, "Member 'UABP_MonsterBase_C::AnimGraphNode_StateResult_3' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_BlendSpacePlayer_5) == 0x000F78, "Member 'UABP_MonsterBase_C::AnimGraphNode_BlendSpacePlayer_5' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_BlendListByBool_6) == 0x000FE8, "Member 'UABP_MonsterBase_C::AnimGraphNode_BlendListByBool_6' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_SequencePlayer_1) == 0x001030, "Member 'UABP_MonsterBase_C::AnimGraphNode_SequencePlayer_1' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_StateResult_2) == 0x001078, "Member 'UABP_MonsterBase_C::AnimGraphNode_StateResult_2' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_SequencePlayer) == 0x001098, "Member 'UABP_MonsterBase_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_StateResult_1) == 0x0010E0, "Member 'UABP_MonsterBase_C::AnimGraphNode_StateResult_1' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_BlendListByBool_5) == 0x001100, "Member 'UABP_MonsterBase_C::AnimGraphNode_BlendListByBool_5' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_BlendSpacePlayer_4) == 0x001148, "Member 'UABP_MonsterBase_C::AnimGraphNode_BlendSpacePlayer_4' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_BlendListByBool_4) == 0x0011B8, "Member 'UABP_MonsterBase_C::AnimGraphNode_BlendListByBool_4' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_BlendListByBool_3) == 0x001200, "Member 'UABP_MonsterBase_C::AnimGraphNode_BlendListByBool_3' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_BlendSpacePlayer_3) == 0x001248, "Member 'UABP_MonsterBase_C::AnimGraphNode_BlendSpacePlayer_3' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_BlendSpacePlayer_2) == 0x0012B8, "Member 'UABP_MonsterBase_C::AnimGraphNode_BlendSpacePlayer_2' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_BlendListByBool_2) == 0x001328, "Member 'UABP_MonsterBase_C::AnimGraphNode_BlendListByBool_2' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_BlendSpacePlayer_1) == 0x001370, "Member 'UABP_MonsterBase_C::AnimGraphNode_BlendSpacePlayer_1' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_BlendSpacePlayer) == 0x0013E0, "Member 'UABP_MonsterBase_C::AnimGraphNode_BlendSpacePlayer' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_StateResult) == 0x001450, "Member 'UABP_MonsterBase_C::AnimGraphNode_StateResult' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_StateMachine) == 0x001470, "Member 'UABP_MonsterBase_C::AnimGraphNode_StateMachine' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_Slot_1) == 0x001538, "Member 'UABP_MonsterBase_C::AnimGraphNode_Slot_1' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_Slot) == 0x001580, "Member 'UABP_MonsterBase_C::AnimGraphNode_Slot' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_LinkedAnimLayer_2) == 0x0015C8, "Member 'UABP_MonsterBase_C::AnimGraphNode_LinkedAnimLayer_2' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_SaveCachedPose_3) == 0x001690, "Member 'UABP_MonsterBase_C::AnimGraphNode_SaveCachedPose_3' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_UseCachedPose_7) == 0x001798, "Member 'UABP_MonsterBase_C::AnimGraphNode_UseCachedPose_7' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_BlendListByBool_1) == 0x0017C0, "Member 'UABP_MonsterBase_C::AnimGraphNode_BlendListByBool_1' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_UseCachedPose_6) == 0x001808, "Member 'UABP_MonsterBase_C::AnimGraphNode_UseCachedPose_6' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_SaveCachedPose_2) == 0x001830, "Member 'UABP_MonsterBase_C::AnimGraphNode_SaveCachedPose_2' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_UseCachedPose_5) == 0x001938, "Member 'UABP_MonsterBase_C::AnimGraphNode_UseCachedPose_5' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_BlendListByBool) == 0x001960, "Member 'UABP_MonsterBase_C::AnimGraphNode_BlendListByBool' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_UseCachedPose_4) == 0x0019A8, "Member 'UABP_MonsterBase_C::AnimGraphNode_UseCachedPose_4' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_LinkedAnimLayer_1) == 0x0019D0, "Member 'UABP_MonsterBase_C::AnimGraphNode_LinkedAnimLayer_1' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_SaveCachedPose_1) == 0x001A98, "Member 'UABP_MonsterBase_C::AnimGraphNode_SaveCachedPose_1' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_UseCachedPose_3) == 0x001BA0, "Member 'UABP_MonsterBase_C::AnimGraphNode_UseCachedPose_3' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_TwoWayBlend) == 0x001BC8, "Member 'UABP_MonsterBase_C::AnimGraphNode_TwoWayBlend' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_UseCachedPose_2) == 0x001C90, "Member 'UABP_MonsterBase_C::AnimGraphNode_UseCachedPose_2' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_LinkedAnimLayer) == 0x001CB8, "Member 'UABP_MonsterBase_C::AnimGraphNode_LinkedAnimLayer' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_SaveCachedPose) == 0x001D80, "Member 'UABP_MonsterBase_C::AnimGraphNode_SaveCachedPose' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_UseCachedPose_1) == 0x001E88, "Member 'UABP_MonsterBase_C::AnimGraphNode_UseCachedPose_1' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AnimGraphNode_UseCachedPose) == 0x001EB0, "Member 'UABP_MonsterBase_C::AnimGraphNode_UseCachedPose' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, K2Node_PropertyAccess_17) == 0x001ED8, "Member 'UABP_MonsterBase_C::K2Node_PropertyAccess_17' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, K2Node_PropertyAccess_15) == 0x001EE0, "Member 'UABP_MonsterBase_C::K2Node_PropertyAccess_15' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, K2Node_PropertyAccess_14) == 0x001EE8, "Member 'UABP_MonsterBase_C::K2Node_PropertyAccess_14' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, K2Node_PropertyAccess_12) == 0x001EF0, "Member 'UABP_MonsterBase_C::K2Node_PropertyAccess_12' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, K2Node_PropertyAccess_10) == 0x001EF4, "Member 'UABP_MonsterBase_C::K2Node_PropertyAccess_10' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, K2Node_PropertyAccess_9) == 0x001EF8, "Member 'UABP_MonsterBase_C::K2Node_PropertyAccess_9' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, K2Node_PropertyAccess_8) == 0x001F00, "Member 'UABP_MonsterBase_C::K2Node_PropertyAccess_8' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, K2Node_PropertyAccess_7) == 0x001F18, "Member 'UABP_MonsterBase_C::K2Node_PropertyAccess_7' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, K2Node_PropertyAccess_6) == 0x001F20, "Member 'UABP_MonsterBase_C::K2Node_PropertyAccess_6' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, K2Node_PropertyAccess_5) == 0x002180, "Member 'UABP_MonsterBase_C::K2Node_PropertyAccess_5' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, K2Node_PropertyAccess_3) == 0x002198, "Member 'UABP_MonsterBase_C::K2Node_PropertyAccess_3' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, K2Node_PropertyAccess_2) == 0x0021B0, "Member 'UABP_MonsterBase_C::K2Node_PropertyAccess_2' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, K2Node_PropertyAccess_1) == 0x0021C8, "Member 'UABP_MonsterBase_C::K2Node_PropertyAccess_1' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, K2Node_PropertyAccess) == 0x0021C9, "Member 'UABP_MonsterBase_C::K2Node_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, __CustomProperty_AimRotator_D409488B47D1A68373AC2E9D883DDF47) == 0x0021D0, "Member 'UABP_MonsterBase_C::__CustomProperty_AimRotator_D409488B47D1A68373AC2E9D883DDF47' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, __CustomProperty_LookAtWorldLocation_FBA1F7A649A7D6231954198C8C515A62) == 0x0021E8, "Member 'UABP_MonsterBase_C::__CustomProperty_LookAtWorldLocation_FBA1F7A649A7D6231954198C8C515A62' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, IsAiming) == 0x002200, "Member 'UABP_MonsterBase_C::IsAiming' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, IsShooting) == 0x002201, "Member 'UABP_MonsterBase_C::IsShooting' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, WeaponAnimInfo) == 0x002208, "Member 'UABP_MonsterBase_C::WeaponAnimInfo' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, CameraVelocityXY) == 0x002468, "Member 'UABP_MonsterBase_C::CameraVelocityXY' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AimRotator) == 0x002478, "Member 'UABP_MonsterBase_C::AimRotator' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, IsLookatEnable) == 0x002490, "Member 'UABP_MonsterBase_C::IsLookatEnable' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, LookAtTarget) == 0x002498, "Member 'UABP_MonsterBase_C::LookAtTarget' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, LookatInTime) == 0x0024B0, "Member 'UABP_MonsterBase_C::LookatInTime' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, LookatOutTime) == 0x0024B8, "Member 'UABP_MonsterBase_C::LookatOutTime' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, IsJumpPreliminary) == 0x0024C0, "Member 'UABP_MonsterBase_C::IsJumpPreliminary' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, IsSkipJumpStart) == 0x0024C1, "Member 'UABP_MonsterBase_C::IsSkipJumpStart' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, AngleSpeed) == 0x0024C8, "Member 'UABP_MonsterBase_C::AngleSpeed' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, IsRiding) == 0x0024D0, "Member 'UABP_MonsterBase_C::IsRiding' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, IsFlying) == 0x0024D1, "Member 'UABP_MonsterBase_C::IsFlying' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, ShouldBeUseShooterComponent) == 0x0024D2, "Member 'UABP_MonsterBase_C::ShouldBeUseShooterComponent' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, ShouldBeUseRiderComponent) == 0x0024D3, "Member 'UABP_MonsterBase_C::ShouldBeUseRiderComponent' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, PrevMoveSpeed) == 0x0024D8, "Member 'UABP_MonsterBase_C::PrevMoveSpeed' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, FootStepEffectClass) == 0x0024E0, "Member 'UABP_MonsterBase_C::FootStepEffectClass' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, FootStepAttachPointName) == 0x0024E8, "Member 'UABP_MonsterBase_C::FootStepAttachPointName' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, FootStepEffect) == 0x0024F0, "Member 'UABP_MonsterBase_C::FootStepEffect' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, TSCached_OwnerPalCharacter) == 0x0024F8, "Member 'UABP_MonsterBase_C::TSCached_OwnerPalCharacter' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, TSCached_ShooterComponent) == 0x002500, "Member 'UABP_MonsterBase_C::TSCached_ShooterComponent' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, TSCached_LookAtComponent) == 0x002508, "Member 'UABP_MonsterBase_C::TSCached_LookAtComponent' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, TSCached_RideMarker) == 0x002510, "Member 'UABP_MonsterBase_C::TSCached_RideMarker' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, IsSpawnDashEffect) == 0x002518, "Member 'UABP_MonsterBase_C::IsSpawnDashEffect' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, DashEffectSpeed) == 0x002520, "Member 'UABP_MonsterBase_C::DashEffectSpeed' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, IsFloating) == 0x002528, "Member 'UABP_MonsterBase_C::IsFloating' has a wrong offset!");
static_assert(offsetof(UABP_MonsterBase_C, MovementScale) == 0x002530, "Member 'UABP_MonsterBase_C::MovementScale' has a wrong offset!");

}

