#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CutsceneActor_Opening

#include "Basic.hpp"

#include "BP_CutsceneActor_Opening_classes.hpp"
#include "BP_CutsceneActor_Opening_parameters.hpp"


namespace SDK
{

// Function BP_CutsceneActor_Opening.BP_CutsceneActor_Opening_C.ExecuteUbergraph_BP_CutsceneActor_Opening
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CutsceneActor_Opening_C::ExecuteUbergraph_BP_CutsceneActor_Opening(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CutsceneActor_Opening_C", "ExecuteUbergraph_BP_CutsceneActor_Opening");

	Params::BP_CutsceneActor_Opening_C_ExecuteUbergraph_BP_CutsceneActor_Opening Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CutsceneActor_Opening.BP_CutsceneActor_Opening_C.OnFinishedCutscene
// (Event, Public, BlueprintEvent)

void ABP_CutsceneActor_Opening_C::OnFinishedCutscene()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CutsceneActor_Opening_C", "OnFinishedCutscene");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CutsceneActor_Opening.BP_CutsceneActor_Opening_C.OnPrePlayCutscene
// (Event, Public, BlueprintEvent)

void ABP_CutsceneActor_Opening_C::OnPrePlayCutscene()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CutsceneActor_Opening_C", "OnPrePlayCutscene");

	UObject::ProcessEvent(Func, nullptr);
}

}

