#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CutsceneLocalPlayer

#include "Basic.hpp"

#include "BP_CutsceneLocalPlayer_classes.hpp"
#include "BP_CutsceneLocalPlayer_parameters.hpp"


namespace SDK
{

// Function BP_CutsceneLocalPlayer.BP_CutsceneLocalPlayer_C.ExecuteUbergraph_BP_CutsceneLocalPlayer
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CutsceneLocalPlayer_C::ExecuteUbergraph_BP_CutsceneLocalPlayer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CutsceneLocalPlayer_C", "ExecuteUbergraph_BP_CutsceneLocalPlayer");

	Params::BP_CutsceneLocalPlayer_C_ExecuteUbergraph_BP_CutsceneLocalPlayer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CutsceneLocalPlayer.BP_CutsceneLocalPlayer_C.LoadLocalPlayerCharaMake
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_CutsceneLocalPlayer_C::LoadLocalPlayerCharaMake()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CutsceneLocalPlayer_C", "LoadLocalPlayerCharaMake");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CutsceneLocalPlayer.BP_CutsceneLocalPlayer_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_CutsceneLocalPlayer_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CutsceneLocalPlayer_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

