#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CutsceneTerminal

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_CutsceneTerminal.BP_CutsceneTerminal_C.ExecuteUbergraph_BP_CutsceneTerminal
// 0x0010 (0x0010 - 0x0000)
struct BP_CutsceneTerminal_C_ExecuteUbergraph_BP_CutsceneTerminal final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_574D[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_DemoOP_TerminalScreen_C*           CallFunc_GetDisplayWidget_TerminalWidget;          // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CutsceneTerminal_C_ExecuteUbergraph_BP_CutsceneTerminal) == 0x000008, "Wrong alignment on BP_CutsceneTerminal_C_ExecuteUbergraph_BP_CutsceneTerminal");
static_assert(sizeof(BP_CutsceneTerminal_C_ExecuteUbergraph_BP_CutsceneTerminal) == 0x000010, "Wrong size on BP_CutsceneTerminal_C_ExecuteUbergraph_BP_CutsceneTerminal");
static_assert(offsetof(BP_CutsceneTerminal_C_ExecuteUbergraph_BP_CutsceneTerminal, EntryPoint) == 0x000000, "Member 'BP_CutsceneTerminal_C_ExecuteUbergraph_BP_CutsceneTerminal::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_CutsceneTerminal_C_ExecuteUbergraph_BP_CutsceneTerminal, CallFunc_GetDisplayWidget_TerminalWidget) == 0x000008, "Member 'BP_CutsceneTerminal_C_ExecuteUbergraph_BP_CutsceneTerminal::CallFunc_GetDisplayWidget_TerminalWidget' has a wrong offset!");

// Function BP_CutsceneTerminal.BP_CutsceneTerminal_C.GetDisplayWidget
// 0x0020 (0x0020 - 0x0000)
struct BP_CutsceneTerminal_C_GetDisplayWidget final
{
public:
	class UWBP_DemoOP_TerminalScreen_C*           TerminalWidget;                                    // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UUserWidget*                            CallFunc_GetWidget_ReturnValue;                    // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_DemoOP_TerminalScreen_C*           K2Node_DynamicCast_AsWBP_Demo_OP_Terminal_Screen;  // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CutsceneTerminal_C_GetDisplayWidget) == 0x000008, "Wrong alignment on BP_CutsceneTerminal_C_GetDisplayWidget");
static_assert(sizeof(BP_CutsceneTerminal_C_GetDisplayWidget) == 0x000020, "Wrong size on BP_CutsceneTerminal_C_GetDisplayWidget");
static_assert(offsetof(BP_CutsceneTerminal_C_GetDisplayWidget, TerminalWidget) == 0x000000, "Member 'BP_CutsceneTerminal_C_GetDisplayWidget::TerminalWidget' has a wrong offset!");
static_assert(offsetof(BP_CutsceneTerminal_C_GetDisplayWidget, CallFunc_GetWidget_ReturnValue) == 0x000008, "Member 'BP_CutsceneTerminal_C_GetDisplayWidget::CallFunc_GetWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CutsceneTerminal_C_GetDisplayWidget, K2Node_DynamicCast_AsWBP_Demo_OP_Terminal_Screen) == 0x000010, "Member 'BP_CutsceneTerminal_C_GetDisplayWidget::K2Node_DynamicCast_AsWBP_Demo_OP_Terminal_Screen' has a wrong offset!");
static_assert(offsetof(BP_CutsceneTerminal_C_GetDisplayWidget, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'BP_CutsceneTerminal_C_GetDisplayWidget::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_CutsceneTerminal_C_GetDisplayWidget, CallFunc_IsValid_ReturnValue) == 0x000019, "Member 'BP_CutsceneTerminal_C_GetDisplayWidget::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function BP_CutsceneTerminal.BP_CutsceneTerminal_C.GetShadowWidget
// 0x0020 (0x0020 - 0x0000)
struct BP_CutsceneTerminal_C_GetShadowWidget final
{
public:
	class UWBP_DemoOP_TerminalShadow_C*           ShadowWidget;                                      // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UUserWidget*                            CallFunc_GetWidget_ReturnValue;                    // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_DemoOP_TerminalShadow_C*           K2Node_DynamicCast_AsWBP_Demo_OP_Terminal_Shadow;  // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CutsceneTerminal_C_GetShadowWidget) == 0x000008, "Wrong alignment on BP_CutsceneTerminal_C_GetShadowWidget");
static_assert(sizeof(BP_CutsceneTerminal_C_GetShadowWidget) == 0x000020, "Wrong size on BP_CutsceneTerminal_C_GetShadowWidget");
static_assert(offsetof(BP_CutsceneTerminal_C_GetShadowWidget, ShadowWidget) == 0x000000, "Member 'BP_CutsceneTerminal_C_GetShadowWidget::ShadowWidget' has a wrong offset!");
static_assert(offsetof(BP_CutsceneTerminal_C_GetShadowWidget, CallFunc_GetWidget_ReturnValue) == 0x000008, "Member 'BP_CutsceneTerminal_C_GetShadowWidget::CallFunc_GetWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CutsceneTerminal_C_GetShadowWidget, K2Node_DynamicCast_AsWBP_Demo_OP_Terminal_Shadow) == 0x000010, "Member 'BP_CutsceneTerminal_C_GetShadowWidget::K2Node_DynamicCast_AsWBP_Demo_OP_Terminal_Shadow' has a wrong offset!");
static_assert(offsetof(BP_CutsceneTerminal_C_GetShadowWidget, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'BP_CutsceneTerminal_C_GetShadowWidget::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_CutsceneTerminal_C_GetShadowWidget, CallFunc_IsValid_ReturnValue) == 0x000019, "Member 'BP_CutsceneTerminal_C_GetShadowWidget::CallFunc_IsValid_ReturnValue' has a wrong offset!");

}

