#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Cutscene_DebrisA

#include "Basic.hpp"

#include "BP_CutsceneCharacterBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Cutscene_DebrisA.BP_Cutscene_DebrisA_C
// 0x00D0 (0x0378 - 0x02A8)
class ABP_Cutscene_DebrisA_C final : public ABP_CutsceneCharacterBase_C
{
public:
	class UStaticMeshComponent*                   SM_BoatWreckage_Debris22;                          // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Debris010;                         // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Debris21;                          // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Boat_chunk03;                      // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Debris20;                          // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Debris19;                          // 0x02D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Debris18;                          // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Debris17;                          // 0x02E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Debris16;                          // 0x02E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Debris15;                          // 0x02F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Debris14;                          // 0x02F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Debris13;                          // 0x0300(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Debris12;                          // 0x0308(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Debris11;                          // 0x0310(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Debris10;                          // 0x0318(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Debris09;                          // 0x0320(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Debris08;                          // 0x0328(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Debris07;                          // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Debris06;                          // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Debris05;                          // 0x0340(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Debris04;                          // 0x0348(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Debris03;                          // 0x0350(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Debris02;                          // 0x0358(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Debris01;                          // 0x0360(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Boat_chunk02;                      // 0x0368(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_BoatWreckage_Boat_chunk01;                      // 0x0370(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Cutscene_DebrisA_C">();
	}
	static class ABP_Cutscene_DebrisA_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Cutscene_DebrisA_C>();
	}
};
static_assert(alignof(ABP_Cutscene_DebrisA_C) == 0x000008, "Wrong alignment on ABP_Cutscene_DebrisA_C");
static_assert(sizeof(ABP_Cutscene_DebrisA_C) == 0x000378, "Wrong size on ABP_Cutscene_DebrisA_C");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Debris22) == 0x0002A8, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Debris22' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Debris010) == 0x0002B0, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Debris010' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Debris21) == 0x0002B8, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Debris21' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Boat_chunk03) == 0x0002C0, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Boat_chunk03' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Debris20) == 0x0002C8, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Debris20' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Debris19) == 0x0002D0, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Debris19' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Debris18) == 0x0002D8, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Debris18' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Debris17) == 0x0002E0, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Debris17' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Debris16) == 0x0002E8, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Debris16' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Debris15) == 0x0002F0, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Debris15' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Debris14) == 0x0002F8, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Debris14' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Debris13) == 0x000300, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Debris13' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Debris12) == 0x000308, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Debris12' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Debris11) == 0x000310, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Debris11' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Debris10) == 0x000318, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Debris10' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Debris09) == 0x000320, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Debris09' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Debris08) == 0x000328, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Debris08' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Debris07) == 0x000330, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Debris07' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Debris06) == 0x000338, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Debris06' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Debris05) == 0x000340, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Debris05' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Debris04) == 0x000348, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Debris04' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Debris03) == 0x000350, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Debris03' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Debris02) == 0x000358, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Debris02' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Debris01) == 0x000360, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Debris01' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Boat_chunk02) == 0x000368, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Boat_chunk02' has a wrong offset!");
static_assert(offsetof(ABP_Cutscene_DebrisA_C, SM_BoatWreckage_Boat_chunk01) == 0x000370, "Member 'ABP_Cutscene_DebrisA_C::SM_BoatWreckage_Boat_chunk01' has a wrong offset!");

}

