#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CutsceneTerminal

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_CutsceneCharacterBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CutsceneTerminal.BP_CutsceneTerminal_C
// 0x0020 (0x02C8 - 0x02A8)
class ABP_CutsceneTerminal_C final : public ABP_CutsceneCharacterBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_CutsceneTerminal_C;              // 0x02A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetComponent*                       Widget_Shadow;                                     // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UWidgetComponent*                       Widget;                                            // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPalSkeletalMeshComponent*              PalSkeletalMesh;                                   // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_CutsceneTerminal(int32 EntryPoint);
	void GetDisplayWidget(class UWBP_DemoOP_TerminalScreen_C** TerminalWidget);
	void GetShadowWidget(class UWBP_DemoOP_TerminalShadow_C** ShadowWidget);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CutsceneTerminal_C">();
	}
	static class ABP_CutsceneTerminal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CutsceneTerminal_C>();
	}
};
static_assert(alignof(ABP_CutsceneTerminal_C) == 0x000008, "Wrong alignment on ABP_CutsceneTerminal_C");
static_assert(sizeof(ABP_CutsceneTerminal_C) == 0x0002C8, "Wrong size on ABP_CutsceneTerminal_C");
static_assert(offsetof(ABP_CutsceneTerminal_C, UberGraphFrame_BP_CutsceneTerminal_C) == 0x0002A8, "Member 'ABP_CutsceneTerminal_C::UberGraphFrame_BP_CutsceneTerminal_C' has a wrong offset!");
static_assert(offsetof(ABP_CutsceneTerminal_C, Widget_Shadow) == 0x0002B0, "Member 'ABP_CutsceneTerminal_C::Widget_Shadow' has a wrong offset!");
static_assert(offsetof(ABP_CutsceneTerminal_C, Widget) == 0x0002B8, "Member 'ABP_CutsceneTerminal_C::Widget' has a wrong offset!");
static_assert(offsetof(ABP_CutsceneTerminal_C, PalSkeletalMesh) == 0x0002C0, "Member 'ABP_CutsceneTerminal_C::PalSkeletalMesh' has a wrong offset!");

}

