#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CutsceneMonsterCharacterBase_PinkCat

#include "Basic.hpp"

#include "BP_CutsceneCharacterBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CutsceneMonsterCharacterBase_PinkCat.BP_CutsceneMonsterCharacterBase_PinkCat_C
// 0x0010 (0x02B8 - 0x02A8)
class ABP_CutsceneMonsterCharacterBase_PinkCat_C final : public ABP_CutsceneCharacterBase_C
{
public:
	class UPalFacialComponent*                    PalFacial;                                         // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CutsceneMonsterCharacterBase_PinkCat_C">();
	}
	static class ABP_CutsceneMonsterCharacterBase_PinkCat_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CutsceneMonsterCharacterBase_PinkCat_C>();
	}
};
static_assert(alignof(ABP_CutsceneMonsterCharacterBase_PinkCat_C) == 0x000008, "Wrong alignment on ABP_CutsceneMonsterCharacterBase_PinkCat_C");
static_assert(sizeof(ABP_CutsceneMonsterCharacterBase_PinkCat_C) == 0x0002B8, "Wrong size on ABP_CutsceneMonsterCharacterBase_PinkCat_C");
static_assert(offsetof(ABP_CutsceneMonsterCharacterBase_PinkCat_C, PalFacial) == 0x0002A8, "Member 'ABP_CutsceneMonsterCharacterBase_PinkCat_C::PalFacial' has a wrong offset!");
static_assert(offsetof(ABP_CutsceneMonsterCharacterBase_PinkCat_C, SkeletalMesh) == 0x0002B0, "Member 'ABP_CutsceneMonsterCharacterBase_PinkCat_C::SkeletalMesh' has a wrong offset!");

}

