#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HUDDispatchParameter_ItemSearch

#include "Basic.hpp"

#include "Pal_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_HUDDispatchParameter_ItemSearch.BP_HUDDispatchParameter_ItemSearch_C
// 0x0018 (0x0050 - 0x0038)
class UBP_HUDDispatchParameter_ItemSearch_C final : public UPalHUDDispatchParameterBase
{
public:
	bool                                          ShowEssential;                                     // 0x0038(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_602A[0x7];                                     // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	FMulticastInlineDelegateProperty_             OnSearchSlotClicked;                               // 0x0040(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void OnSearchSlotClicked__DelegateSignature(class FName StaticItemId);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_HUDDispatchParameter_ItemSearch_C">();
	}
	static class UBP_HUDDispatchParameter_ItemSearch_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_HUDDispatchParameter_ItemSearch_C>();
	}
};
static_assert(alignof(UBP_HUDDispatchParameter_ItemSearch_C) == 0x000008, "Wrong alignment on UBP_HUDDispatchParameter_ItemSearch_C");
static_assert(sizeof(UBP_HUDDispatchParameter_ItemSearch_C) == 0x000050, "Wrong size on UBP_HUDDispatchParameter_ItemSearch_C");
static_assert(offsetof(UBP_HUDDispatchParameter_ItemSearch_C, ShowEssential) == 0x000038, "Member 'UBP_HUDDispatchParameter_ItemSearch_C::ShowEssential' has a wrong offset!");
static_assert(offsetof(UBP_HUDDispatchParameter_ItemSearch_C, OnSearchSlotClicked) == 0x000040, "Member 'UBP_HUDDispatchParameter_ItemSearch_C::OnSearchSlotClicked' has a wrong offset!");

}

