#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HUDDispatchParameter_TechnologyFilter

#include "Basic.hpp"

#include "Pal_structs.hpp"


namespace SDK::Params
{

// Function BP_HUDDispatchParameter_TechnologyFilter.BP_HUDDispatchParameter_TechnologyFilter_C.OnFilterApplied__DelegateSignature
// 0x00A8 (0x00A8 - 0x0000)
struct BP_HUDDispatchParameter_TechnologyFilter_C_OnFilterApplied__DelegateSignature final
{
public:
	TSet<EPalItemTypeA>                           ItemFilter;                                        // 0x0000(0x0050)(BlueprintVisible, BlueprintReadOnly, Parm)
	TSet<EPalBuildObjectTypeA>                    BuiltFilter;                                       // 0x0050(0x0050)(BlueprintVisible, BlueprintReadOnly, Parm)
	bool                                          Param_ShowUnlocked;                                // 0x00A0(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_HUDDispatchParameter_TechnologyFilter_C_OnFilterApplied__DelegateSignature) == 0x000008, "Wrong alignment on BP_HUDDispatchParameter_TechnologyFilter_C_OnFilterApplied__DelegateSignature");
static_assert(sizeof(BP_HUDDispatchParameter_TechnologyFilter_C_OnFilterApplied__DelegateSignature) == 0x0000A8, "Wrong size on BP_HUDDispatchParameter_TechnologyFilter_C_OnFilterApplied__DelegateSignature");
static_assert(offsetof(BP_HUDDispatchParameter_TechnologyFilter_C_OnFilterApplied__DelegateSignature, ItemFilter) == 0x000000, "Member 'BP_HUDDispatchParameter_TechnologyFilter_C_OnFilterApplied__DelegateSignature::ItemFilter' has a wrong offset!");
static_assert(offsetof(BP_HUDDispatchParameter_TechnologyFilter_C_OnFilterApplied__DelegateSignature, BuiltFilter) == 0x000050, "Member 'BP_HUDDispatchParameter_TechnologyFilter_C_OnFilterApplied__DelegateSignature::BuiltFilter' has a wrong offset!");
static_assert(offsetof(BP_HUDDispatchParameter_TechnologyFilter_C_OnFilterApplied__DelegateSignature, Param_ShowUnlocked) == 0x0000A0, "Member 'BP_HUDDispatchParameter_TechnologyFilter_C_OnFilterApplied__DelegateSignature::Param_ShowUnlocked' has a wrong offset!");

}

