#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MonoNPCSpawnerBossBase_BOSS_Male_People03

#include "Basic.hpp"

#include "BP_MonoNPCSpawnerBossBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MonoNPCSpawnerBossBase_BOSS_Male_People03.BP_MonoNPCSpawnerBossBase_BOSS_Male_People03_C
// 0x0000 (0x0448 - 0x0448)
class ABP_MonoNPCSpawnerBossBase_BOSS_Male_People03_C final : public ABP_MonoNPCSpawnerBossBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MonoNPCSpawnerBossBase_BOSS_Male_People03_C">();
	}
	static class ABP_MonoNPCSpawnerBossBase_BOSS_Male_People03_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MonoNPCSpawnerBossBase_BOSS_Male_People03_C>();
	}
};
static_assert(alignof(ABP_MonoNPCSpawnerBossBase_BOSS_Male_People03_C) == 0x000008, "Wrong alignment on ABP_MonoNPCSpawnerBossBase_BOSS_Male_People03_C");
static_assert(sizeof(ABP_MonoNPCSpawnerBossBase_BOSS_Male_People03_C) == 0x000448, "Wrong size on ABP_MonoNPCSpawnerBossBase_BOSS_Male_People03_C");

}

