#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PalPlayerState

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PalPlayerState.BP_PalPlayerState_C
// 0x0010 (0x09B0 - 0x09A0)
class ABP_PalPlayerState_C final : public APalPlayerState
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x09A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x09A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_PalPlayerState(int32 EntryPoint);
	void HostLocalWorldSave(bool SaveSuccess);
	void LoadTitleLevel(bool bIsSaveSuccess);
	void ProcessSaveReturn();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PalPlayerState_C">();
	}
	static class ABP_PalPlayerState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PalPlayerState_C>();
	}
};
static_assert(alignof(ABP_PalPlayerState_C) == 0x000010, "Wrong alignment on ABP_PalPlayerState_C");
static_assert(sizeof(ABP_PalPlayerState_C) == 0x0009B0, "Wrong size on ABP_PalPlayerState_C");
static_assert(offsetof(ABP_PalPlayerState_C, UberGraphFrame) == 0x0009A0, "Member 'ABP_PalPlayerState_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_PalPlayerState_C, DefaultSceneRoot) == 0x0009A8, "Member 'ABP_PalPlayerState_C::DefaultSceneRoot' has a wrong offset!");

}

