#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RocketLauncher

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_AssaultRifleBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_RocketLauncher.BP_RocketLauncher_C
// 0x0030 (0x0600 - 0x05D0)
class ABP_RocketLauncher_C : public ABP_AssaultRifleBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_RocketLauncher_C;                // 0x05D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   Sphere;                                            // 0x05D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   BP_Ammo_Rocket;                                    // 0x05E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x05E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               RocketMask;                                        // 0x05F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           ReloadTimerHandle;                                 // 0x05F8(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ChangeTransformForRocketReload(const struct FVector& Location, const struct FRotator& Rotation);
	void ChangeTransformForRocketWhenReloadIsDone(const struct FVector& Location, const struct FRotator& Lotation);
	void ExecuteUbergraph_BP_RocketLauncher(int32 EntryPoint);
	void Get_Right_Hand_Location(struct FVector* RightHandLocation);
	void GetAimingBlurAngle(double* Angle);
	void GetBackFireLocation(struct FVector* Location, struct FRotator* Rotation);
	void GetBlurAngle(double* Angle);
	void GetBulletClass(class UClass** NewParam);
	void GetInitializeInterval(double* Time);
	void GetMuzzleEffect(class UNiagaraSystem** NewParam);
	void GetMuzzleLocation(struct FVector* MuzzleLocation);
	void GetMuzzleRotator(struct FRotator* Rotator);
	void GetShootInterval(double* Time);
	void IsUseRightHandAttach(bool* IsUse);
	void OnAttachWeapon(class AActor* AttachActor);
	void OnDetachWeapon(class AActor* DetachActor);
	void OnEndShootAnimation(class UAnimMontage* Montage);
	void OnPullTrigger();
	void OnReload(int32 bulletsNum);
	void OnReloadStart();
	void OnShoot(class APalBullet* BulletActor);
	void OnStopReload();
	void PlayFireSound();
	void PlayReloadSound();
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);
	void ShootBullet();
	void StopReloadSound();
	void ________();

	struct FTransform GetLeftHandTransform() const;
	bool IsUseLeftHandAttach() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_RocketLauncher_C">();
	}
	static class ABP_RocketLauncher_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RocketLauncher_C>();
	}
};
static_assert(alignof(ABP_RocketLauncher_C) == 0x000008, "Wrong alignment on ABP_RocketLauncher_C");
static_assert(sizeof(ABP_RocketLauncher_C) == 0x000600, "Wrong size on ABP_RocketLauncher_C");
static_assert(offsetof(ABP_RocketLauncher_C, UberGraphFrame_BP_RocketLauncher_C) == 0x0005D0, "Member 'ABP_RocketLauncher_C::UberGraphFrame_BP_RocketLauncher_C' has a wrong offset!");
static_assert(offsetof(ABP_RocketLauncher_C, Sphere) == 0x0005D8, "Member 'ABP_RocketLauncher_C::Sphere' has a wrong offset!");
static_assert(offsetof(ABP_RocketLauncher_C, BP_Ammo_Rocket) == 0x0005E0, "Member 'ABP_RocketLauncher_C::BP_Ammo_Rocket' has a wrong offset!");
static_assert(offsetof(ABP_RocketLauncher_C, SkeletalMesh) == 0x0005E8, "Member 'ABP_RocketLauncher_C::SkeletalMesh' has a wrong offset!");
static_assert(offsetof(ABP_RocketLauncher_C, RocketMask) == 0x0005F0, "Member 'ABP_RocketLauncher_C::RocketMask' has a wrong offset!");
static_assert(offsetof(ABP_RocketLauncher_C, ReloadTimerHandle) == 0x0005F8, "Member 'ABP_RocketLauncher_C::ReloadTimerHandle' has a wrong offset!");

}

