#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SheepBall

#include "Basic.hpp"

#include "BP_MonsterBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SheepBall.BP_SheepBall_C
// 0x0020 (0x0B20 - 0x0B00)
class ABP_SheepBall_C final : public ABP_MonsterBase_C
{
public:
	class UPalBodyPartsSphereComponent*           PalBodyPartsSphere1;                               // 0x0B00(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USphereComponent*                       Shield;                                            // 0x0B08(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_CoopParam_Shield_C*                 BP_CoopParam_Sheild;                               // 0x0B10(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPalBodyPartsSphereComponent*           PalBodyPartsSphere;                                // 0x0B18(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SheepBall_C">();
	}
	static class ABP_SheepBall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SheepBall_C>();
	}
};
static_assert(alignof(ABP_SheepBall_C) == 0x000010, "Wrong alignment on ABP_SheepBall_C");
static_assert(sizeof(ABP_SheepBall_C) == 0x000B20, "Wrong size on ABP_SheepBall_C");
static_assert(offsetof(ABP_SheepBall_C, PalBodyPartsSphere1) == 0x000B00, "Member 'ABP_SheepBall_C::PalBodyPartsSphere1' has a wrong offset!");
static_assert(offsetof(ABP_SheepBall_C, Shield) == 0x000B08, "Member 'ABP_SheepBall_C::Shield' has a wrong offset!");
static_assert(offsetof(ABP_SheepBall_C, BP_CoopParam_Sheild) == 0x000B10, "Member 'ABP_SheepBall_C::BP_CoopParam_Sheild' has a wrong offset!");
static_assert(offsetof(ABP_SheepBall_C, PalBodyPartsSphere) == 0x000B18, "Member 'ABP_SheepBall_C::PalBodyPartsSphere' has a wrong offset!");

}

