#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LS_Opening_04

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "LevelSequence_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LS_Opening_04.LS_Opening_04 (Director BP)_C
// 0x0008 (0x0040 - 0x0038)
class ULS_Opening_04__Director_BP__C final : public ULevelSequenceDirector
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0038(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_LS_Opening_04__Director_BP_(int32 EntryPoint);
	void SequenceEvent__ENTRYPOINTLS_Opening_04__Director_BP_(class ABP_CutsceneTerminal_C* BP_Cutscene_Terminal);
	void TriggerTerminalWidgetAnim(class ABP_CutsceneTerminal_C* BP_Cutscene_Terminal);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LS_Opening_04 (Director BP)_C">();
	}
	static class ULS_Opening_04__Director_BP__C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULS_Opening_04__Director_BP__C>();
	}
};
static_assert(alignof(ULS_Opening_04__Director_BP__C) == 0x000008, "Wrong alignment on ULS_Opening_04__Director_BP__C");
static_assert(sizeof(ULS_Opening_04__Director_BP__C) == 0x000040, "Wrong size on ULS_Opening_04__Director_BP__C");
static_assert(offsetof(ULS_Opening_04__Director_BP__C, UberGraphFrame) == 0x000038, "Member 'ULS_Opening_04__Director_BP__C::UberGraphFrame' has a wrong offset!");

}

