#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LS_Opening_04

#include "Basic.hpp"

#include "LS_Opening_04_classes.hpp"
#include "LS_Opening_04_parameters.hpp"


namespace SDK
{

// Function LS_Opening_04.LS_Opening_04 (Director BP)_C.ExecuteUbergraph_LS_Opening_04 (Director BP)
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULS_Opening_04__Director_BP__C::ExecuteUbergraph_LS_Opening_04__Director_BP_(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_Opening_04 (Director BP)_C", "ExecuteUbergraph_LS_Opening_04 (Director BP)");

	Params::LS_Opening_04__Director_BP__C_ExecuteUbergraph_LS_Opening_04__Director_BP_ Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LS_Opening_04.LS_Opening_04 (Director BP)_C.SequenceEvent__ENTRYPOINTLS_Opening_04 (Director BP)
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_CutsceneTerminal_C*           BP_Cutscene_Terminal                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ULS_Opening_04__Director_BP__C::SequenceEvent__ENTRYPOINTLS_Opening_04__Director_BP_(class ABP_CutsceneTerminal_C* BP_Cutscene_Terminal)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_Opening_04 (Director BP)_C", "SequenceEvent__ENTRYPOINTLS_Opening_04 (Director BP)");

	Params::LS_Opening_04__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_04__Director_BP_ Parms{};

	Parms.BP_Cutscene_Terminal = BP_Cutscene_Terminal;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LS_Opening_04.LS_Opening_04 (Director BP)_C.TriggerTerminalWidgetAnim
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_CutsceneTerminal_C*           BP_Cutscene_Terminal                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ULS_Opening_04__Director_BP__C::TriggerTerminalWidgetAnim(class ABP_CutsceneTerminal_C* BP_Cutscene_Terminal)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_Opening_04 (Director BP)_C", "TriggerTerminalWidgetAnim");

	Params::LS_Opening_04__Director_BP__C_TriggerTerminalWidgetAnim Parms{};

	Parms.BP_Cutscene_Terminal = BP_Cutscene_Terminal;

	UObject::ProcessEvent(Func, &Parms);
}

}

