#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LS_Opening_02

#include "Basic.hpp"

#include "Pal_structs.hpp"


namespace SDK::Params
{

// Function LS_Opening_02.LS_Opening_02 (Director BP)_C.ExecuteUbergraph_LS_Opening_02 (Director BP)
// 0x0070 (0x0070 - 0x0000)
struct LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_ final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5857[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalFacialComponent*                    K2Node_CustomEvent_PalFacial_1;                    // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	EPalFacialEyeType                             K2Node_CustomEvent_Eye;                            // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5858[0x7];                                     // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalFacialComponent*                    K2Node_CustomEvent_PalFacial;                      // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	EPalFacialMouthType                           K2Node_CustomEvent_Mouth;                          // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5859[0x7];                                     // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetLocalPlayerController_ReturnValue;     // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalFacialComponent*                    K2Node_CustomEvent_PalFacial_2;                    // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	EPalFacialMouthType                           K2Node_CustomEvent_Mouth_1;                        // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_585A[0x7];                                     // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_DemoOP_EyeTransition_C*            CallFunc_Create_ReturnValue;                       // 0x0040(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPalFacialComponent*                    K2Node_CustomEvent_PalFacial_3;                    // 0x0048(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	EPalFacialEyeType                             K2Node_CustomEvent_Eye_1;                          // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_585B[0x7];                                     // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0060(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_) == 0x000008, "Wrong alignment on LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_");
static_assert(sizeof(LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_) == 0x000070, "Wrong size on LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_");
static_assert(offsetof(LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_, EntryPoint) == 0x000000, "Member 'LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_::EntryPoint' has a wrong offset!");
static_assert(offsetof(LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_, K2Node_CustomEvent_PalFacial_1) == 0x000008, "Member 'LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_::K2Node_CustomEvent_PalFacial_1' has a wrong offset!");
static_assert(offsetof(LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_, K2Node_CustomEvent_Eye) == 0x000010, "Member 'LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_::K2Node_CustomEvent_Eye' has a wrong offset!");
static_assert(offsetof(LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_, K2Node_CustomEvent_PalFacial) == 0x000018, "Member 'LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_::K2Node_CustomEvent_PalFacial' has a wrong offset!");
static_assert(offsetof(LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_, K2Node_CustomEvent_Mouth) == 0x000020, "Member 'LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_::K2Node_CustomEvent_Mouth' has a wrong offset!");
static_assert(offsetof(LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_, CallFunc_GetLocalPlayerController_ReturnValue) == 0x000028, "Member 'LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_::CallFunc_GetLocalPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_, K2Node_CustomEvent_PalFacial_2) == 0x000030, "Member 'LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_::K2Node_CustomEvent_PalFacial_2' has a wrong offset!");
static_assert(offsetof(LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_, K2Node_CustomEvent_Mouth_1) == 0x000038, "Member 'LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_::K2Node_CustomEvent_Mouth_1' has a wrong offset!");
static_assert(offsetof(LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_, CallFunc_Create_ReturnValue) == 0x000040, "Member 'LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_, K2Node_CustomEvent_PalFacial_3) == 0x000048, "Member 'LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_::K2Node_CustomEvent_PalFacial_3' has a wrong offset!");
static_assert(offsetof(LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_, K2Node_CustomEvent_Eye_1) == 0x000050, "Member 'LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_::K2Node_CustomEvent_Eye_1' has a wrong offset!");
static_assert(offsetof(LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_, CallFunc_PlayAnimation_ReturnValue) == 0x000058, "Member 'LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_, K2Node_CreateDelegate_OutputDelegate) == 0x000060, "Member 'LS_Opening_02__Director_BP__C_ExecuteUbergraph_LS_Opening_02__Director_BP_::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");

// Function LS_Opening_02.LS_Opening_02 (Director BP)_C.PalFacial_Event_0
// 0x0010 (0x0010 - 0x0000)
struct LS_Opening_02__Director_BP__C_PalFacial_Event_0 final
{
public:
	class UPalFacialComponent*                    PalFacial;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	EPalFacialEyeType                             Eye;                                               // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(LS_Opening_02__Director_BP__C_PalFacial_Event_0) == 0x000008, "Wrong alignment on LS_Opening_02__Director_BP__C_PalFacial_Event_0");
static_assert(sizeof(LS_Opening_02__Director_BP__C_PalFacial_Event_0) == 0x000010, "Wrong size on LS_Opening_02__Director_BP__C_PalFacial_Event_0");
static_assert(offsetof(LS_Opening_02__Director_BP__C_PalFacial_Event_0, PalFacial) == 0x000000, "Member 'LS_Opening_02__Director_BP__C_PalFacial_Event_0::PalFacial' has a wrong offset!");
static_assert(offsetof(LS_Opening_02__Director_BP__C_PalFacial_Event_0, Eye) == 0x000008, "Member 'LS_Opening_02__Director_BP__C_PalFacial_Event_0::Eye' has a wrong offset!");

// Function LS_Opening_02.LS_Opening_02 (Director BP)_C.PalFacial_Event_1
// 0x0010 (0x0010 - 0x0000)
struct LS_Opening_02__Director_BP__C_PalFacial_Event_1 final
{
public:
	class UPalFacialComponent*                    PalFacial;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	EPalFacialMouthType                           Mouth;                                             // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(LS_Opening_02__Director_BP__C_PalFacial_Event_1) == 0x000008, "Wrong alignment on LS_Opening_02__Director_BP__C_PalFacial_Event_1");
static_assert(sizeof(LS_Opening_02__Director_BP__C_PalFacial_Event_1) == 0x000010, "Wrong size on LS_Opening_02__Director_BP__C_PalFacial_Event_1");
static_assert(offsetof(LS_Opening_02__Director_BP__C_PalFacial_Event_1, PalFacial) == 0x000000, "Member 'LS_Opening_02__Director_BP__C_PalFacial_Event_1::PalFacial' has a wrong offset!");
static_assert(offsetof(LS_Opening_02__Director_BP__C_PalFacial_Event_1, Mouth) == 0x000008, "Member 'LS_Opening_02__Director_BP__C_PalFacial_Event_1::Mouth' has a wrong offset!");

// Function LS_Opening_02.LS_Opening_02 (Director BP)_C.PalFacial_Event_2
// 0x0010 (0x0010 - 0x0000)
struct LS_Opening_02__Director_BP__C_PalFacial_Event_2 final
{
public:
	class UPalFacialComponent*                    PalFacial;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	EPalFacialEyeType                             Eye;                                               // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(LS_Opening_02__Director_BP__C_PalFacial_Event_2) == 0x000008, "Wrong alignment on LS_Opening_02__Director_BP__C_PalFacial_Event_2");
static_assert(sizeof(LS_Opening_02__Director_BP__C_PalFacial_Event_2) == 0x000010, "Wrong size on LS_Opening_02__Director_BP__C_PalFacial_Event_2");
static_assert(offsetof(LS_Opening_02__Director_BP__C_PalFacial_Event_2, PalFacial) == 0x000000, "Member 'LS_Opening_02__Director_BP__C_PalFacial_Event_2::PalFacial' has a wrong offset!");
static_assert(offsetof(LS_Opening_02__Director_BP__C_PalFacial_Event_2, Eye) == 0x000008, "Member 'LS_Opening_02__Director_BP__C_PalFacial_Event_2::Eye' has a wrong offset!");

// Function LS_Opening_02.LS_Opening_02 (Director BP)_C.PalFacial_Event_3
// 0x0010 (0x0010 - 0x0000)
struct LS_Opening_02__Director_BP__C_PalFacial_Event_3 final
{
public:
	class UPalFacialComponent*                    PalFacial;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	EPalFacialMouthType                           Mouth;                                             // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(LS_Opening_02__Director_BP__C_PalFacial_Event_3) == 0x000008, "Wrong alignment on LS_Opening_02__Director_BP__C_PalFacial_Event_3");
static_assert(sizeof(LS_Opening_02__Director_BP__C_PalFacial_Event_3) == 0x000010, "Wrong size on LS_Opening_02__Director_BP__C_PalFacial_Event_3");
static_assert(offsetof(LS_Opening_02__Director_BP__C_PalFacial_Event_3, PalFacial) == 0x000000, "Member 'LS_Opening_02__Director_BP__C_PalFacial_Event_3::PalFacial' has a wrong offset!");
static_assert(offsetof(LS_Opening_02__Director_BP__C_PalFacial_Event_3, Mouth) == 0x000008, "Member 'LS_Opening_02__Director_BP__C_PalFacial_Event_3::Mouth' has a wrong offset!");

// Function LS_Opening_02.LS_Opening_02 (Director BP)_C.SequenceEvent__ENTRYPOINTLS_Opening_02 (Director BP)
// 0x0008 (0x0008 - 0x0000)
struct LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP_ final
{
public:
	class UPalFacialComponent*                    PalFacial;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP_) == 0x000008, "Wrong alignment on LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP_");
static_assert(sizeof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP_) == 0x000008, "Wrong size on LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP_");
static_assert(offsetof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP_, PalFacial) == 0x000000, "Member 'LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP_::PalFacial' has a wrong offset!");

// Function LS_Opening_02.LS_Opening_02 (Director BP)_C.SequenceEvent__ENTRYPOINTLS_Opening_02 (Director BP)_0
// 0x0008 (0x0008 - 0x0000)
struct LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__0 final
{
public:
	class UPalFacialComponent*                    PalFacial;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__0) == 0x000008, "Wrong alignment on LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__0");
static_assert(sizeof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__0) == 0x000008, "Wrong size on LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__0");
static_assert(offsetof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__0, PalFacial) == 0x000000, "Member 'LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__0::PalFacial' has a wrong offset!");

// Function LS_Opening_02.LS_Opening_02 (Director BP)_C.SequenceEvent__ENTRYPOINTLS_Opening_02 (Director BP)_1
// 0x0008 (0x0008 - 0x0000)
struct LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__1 final
{
public:
	class UPalFacialComponent*                    PalFacial;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__1) == 0x000008, "Wrong alignment on LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__1");
static_assert(sizeof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__1) == 0x000008, "Wrong size on LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__1");
static_assert(offsetof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__1, PalFacial) == 0x000000, "Member 'LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__1::PalFacial' has a wrong offset!");

// Function LS_Opening_02.LS_Opening_02 (Director BP)_C.SequenceEvent__ENTRYPOINTLS_Opening_02 (Director BP)_2
// 0x0008 (0x0008 - 0x0000)
struct LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__2 final
{
public:
	class UPalFacialComponent*                    PalFacial;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__2) == 0x000008, "Wrong alignment on LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__2");
static_assert(sizeof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__2) == 0x000008, "Wrong size on LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__2");
static_assert(offsetof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__2, PalFacial) == 0x000000, "Member 'LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__2::PalFacial' has a wrong offset!");

// Function LS_Opening_02.LS_Opening_02 (Director BP)_C.SequenceEvent__ENTRYPOINTLS_Opening_02 (Director BP)_3
// 0x0008 (0x0008 - 0x0000)
struct LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__3 final
{
public:
	class UPalFacialComponent*                    PalFacial;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__3) == 0x000008, "Wrong alignment on LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__3");
static_assert(sizeof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__3) == 0x000008, "Wrong size on LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__3");
static_assert(offsetof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__3, PalFacial) == 0x000000, "Member 'LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__3::PalFacial' has a wrong offset!");

// Function LS_Opening_02.LS_Opening_02 (Director BP)_C.SequenceEvent__ENTRYPOINTLS_Opening_02 (Director BP)_4
// 0x0008 (0x0008 - 0x0000)
struct LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__4 final
{
public:
	class UPalFacialComponent*                    PalFacial;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__4) == 0x000008, "Wrong alignment on LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__4");
static_assert(sizeof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__4) == 0x000008, "Wrong size on LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__4");
static_assert(offsetof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__4, PalFacial) == 0x000000, "Member 'LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__4::PalFacial' has a wrong offset!");

// Function LS_Opening_02.LS_Opening_02 (Director BP)_C.SequenceEvent__ENTRYPOINTLS_Opening_02 (Director BP)_5
// 0x0008 (0x0008 - 0x0000)
struct LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__5 final
{
public:
	class UPalFacialComponent*                    PalFacial;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__5) == 0x000008, "Wrong alignment on LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__5");
static_assert(sizeof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__5) == 0x000008, "Wrong size on LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__5");
static_assert(offsetof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__5, PalFacial) == 0x000000, "Member 'LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__5::PalFacial' has a wrong offset!");

// Function LS_Opening_02.LS_Opening_02 (Director BP)_C.SequenceEvent__ENTRYPOINTLS_Opening_02 (Director BP)_6
// 0x0008 (0x0008 - 0x0000)
struct LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__6 final
{
public:
	class UPalFacialComponent*                    PalFacial;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__6) == 0x000008, "Wrong alignment on LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__6");
static_assert(sizeof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__6) == 0x000008, "Wrong size on LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__6");
static_assert(offsetof(LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__6, PalFacial) == 0x000000, "Member 'LS_Opening_02__Director_BP__C_SequenceEvent__ENTRYPOINTLS_Opening_02__Director_BP__6::PalFacial' has a wrong offset!");

}

