#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BossWarningLoupe

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function WBP_BossWarningLoupe.WBP_BossWarningLoupe_C.CalcScreenPosition
// 0x00A8 (0x00A8 - 0x0000)
struct WBP_BossWarningLoupe_C_CalcScreenPosition final
{
public:
	struct FVector                                CallFunc_GetTargetWorldLocation_outVector;         // 0x0000(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetLocalPlayerController_ReturnValue;     // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_62D8[0x7];                                     // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CallFunc_GetCameraRotation_ReturnValue;            // 0x0028(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_GetForwardVector_ReturnValue;             // 0x0040(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0058(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x0070(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Normal_ReturnValue;                       // 0x0088(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Dot_VectorVector_ReturnValue;             // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BossWarningLoupe_C_CalcScreenPosition) == 0x000008, "Wrong alignment on WBP_BossWarningLoupe_C_CalcScreenPosition");
static_assert(sizeof(WBP_BossWarningLoupe_C_CalcScreenPosition) == 0x0000A8, "Wrong size on WBP_BossWarningLoupe_C_CalcScreenPosition");
static_assert(offsetof(WBP_BossWarningLoupe_C_CalcScreenPosition, CallFunc_GetTargetWorldLocation_outVector) == 0x000000, "Member 'WBP_BossWarningLoupe_C_CalcScreenPosition::CallFunc_GetTargetWorldLocation_outVector' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_CalcScreenPosition, CallFunc_GetLocalPlayerController_ReturnValue) == 0x000018, "Member 'WBP_BossWarningLoupe_C_CalcScreenPosition::CallFunc_GetLocalPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_CalcScreenPosition, CallFunc_IsValid_ReturnValue) == 0x000020, "Member 'WBP_BossWarningLoupe_C_CalcScreenPosition::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_CalcScreenPosition, CallFunc_GetCameraRotation_ReturnValue) == 0x000028, "Member 'WBP_BossWarningLoupe_C_CalcScreenPosition::CallFunc_GetCameraRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_CalcScreenPosition, CallFunc_GetForwardVector_ReturnValue) == 0x000040, "Member 'WBP_BossWarningLoupe_C_CalcScreenPosition::CallFunc_GetForwardVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_CalcScreenPosition, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000058, "Member 'WBP_BossWarningLoupe_C_CalcScreenPosition::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_CalcScreenPosition, CallFunc_Subtract_VectorVector_ReturnValue) == 0x000070, "Member 'WBP_BossWarningLoupe_C_CalcScreenPosition::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_CalcScreenPosition, CallFunc_Normal_ReturnValue) == 0x000088, "Member 'WBP_BossWarningLoupe_C_CalcScreenPosition::CallFunc_Normal_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_CalcScreenPosition, CallFunc_Dot_VectorVector_ReturnValue) == 0x0000A0, "Member 'WBP_BossWarningLoupe_C_CalcScreenPosition::CallFunc_Dot_VectorVector_ReturnValue' has a wrong offset!");

// Function WBP_BossWarningLoupe.WBP_BossWarningLoupe_C.GetLoupeWidgetSize
// 0x0028 (0x0028 - 0x0000)
struct WBP_BossWarningLoupe_C_GetLoupeWidgetSize final
{
public:
	struct FVector2D                              Param_WidgetSize;                                  // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanelSlot*                       CallFunc_SlotAsCanvasSlot_ReturnValue;             // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_GetSize_ReturnValue;                      // 0x0018(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BossWarningLoupe_C_GetLoupeWidgetSize) == 0x000008, "Wrong alignment on WBP_BossWarningLoupe_C_GetLoupeWidgetSize");
static_assert(sizeof(WBP_BossWarningLoupe_C_GetLoupeWidgetSize) == 0x000028, "Wrong size on WBP_BossWarningLoupe_C_GetLoupeWidgetSize");
static_assert(offsetof(WBP_BossWarningLoupe_C_GetLoupeWidgetSize, Param_WidgetSize) == 0x000000, "Member 'WBP_BossWarningLoupe_C_GetLoupeWidgetSize::Param_WidgetSize' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_GetLoupeWidgetSize, CallFunc_SlotAsCanvasSlot_ReturnValue) == 0x000010, "Member 'WBP_BossWarningLoupe_C_GetLoupeWidgetSize::CallFunc_SlotAsCanvasSlot_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_GetLoupeWidgetSize, CallFunc_GetSize_ReturnValue) == 0x000018, "Member 'WBP_BossWarningLoupe_C_GetLoupeWidgetSize::CallFunc_GetSize_ReturnValue' has a wrong offset!");

// Function WBP_BossWarningLoupe.WBP_BossWarningLoupe_C.GetTargetWidgetSize
// 0x0028 (0x0028 - 0x0000)
struct WBP_BossWarningLoupe_C_GetTargetWidgetSize final
{
public:
	struct FVector2D                              OutVector;                                         // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanelSlot*                       CallFunc_SlotAsCanvasSlot_ReturnValue;             // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_GetSize_ReturnValue;                      // 0x0018(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BossWarningLoupe_C_GetTargetWidgetSize) == 0x000008, "Wrong alignment on WBP_BossWarningLoupe_C_GetTargetWidgetSize");
static_assert(sizeof(WBP_BossWarningLoupe_C_GetTargetWidgetSize) == 0x000028, "Wrong size on WBP_BossWarningLoupe_C_GetTargetWidgetSize");
static_assert(offsetof(WBP_BossWarningLoupe_C_GetTargetWidgetSize, OutVector) == 0x000000, "Member 'WBP_BossWarningLoupe_C_GetTargetWidgetSize::OutVector' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_GetTargetWidgetSize, CallFunc_SlotAsCanvasSlot_ReturnValue) == 0x000010, "Member 'WBP_BossWarningLoupe_C_GetTargetWidgetSize::CallFunc_SlotAsCanvasSlot_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_GetTargetWidgetSize, CallFunc_GetSize_ReturnValue) == 0x000018, "Member 'WBP_BossWarningLoupe_C_GetTargetWidgetSize::CallFunc_GetSize_ReturnValue' has a wrong offset!");

// Function WBP_BossWarningLoupe.WBP_BossWarningLoupe_C.GetTargetWorldLocation
// 0x0040 (0x0040 - 0x0000)
struct WBP_BossWarningLoupe_C_GetTargetWorldLocation final
{
public:
	struct FVector                                OutVector;                                         // 0x0000(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          CallFunc_TryGetIndividualActor_ReturnValue;        // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_62D9[0x6];                                     // 0x0022(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0028(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BossWarningLoupe_C_GetTargetWorldLocation) == 0x000008, "Wrong alignment on WBP_BossWarningLoupe_C_GetTargetWorldLocation");
static_assert(sizeof(WBP_BossWarningLoupe_C_GetTargetWorldLocation) == 0x000040, "Wrong size on WBP_BossWarningLoupe_C_GetTargetWorldLocation");
static_assert(offsetof(WBP_BossWarningLoupe_C_GetTargetWorldLocation, OutVector) == 0x000000, "Member 'WBP_BossWarningLoupe_C_GetTargetWorldLocation::OutVector' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_GetTargetWorldLocation, CallFunc_TryGetIndividualActor_ReturnValue) == 0x000018, "Member 'WBP_BossWarningLoupe_C_GetTargetWorldLocation::CallFunc_TryGetIndividualActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_GetTargetWorldLocation, CallFunc_IsValid_ReturnValue) == 0x000020, "Member 'WBP_BossWarningLoupe_C_GetTargetWorldLocation::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_GetTargetWorldLocation, CallFunc_IsValid_ReturnValue_1) == 0x000021, "Member 'WBP_BossWarningLoupe_C_GetTargetWorldLocation::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_GetTargetWorldLocation, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000028, "Member 'WBP_BossWarningLoupe_C_GetTargetWorldLocation::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");

// Function WBP_BossWarningLoupe.WBP_BossWarningLoupe_C.IsEnableLoupe
// 0x0078 (0x0078 - 0x0000)
struct WBP_BossWarningLoupe_C_IsEnableLoupe final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_62DA[0x7];                                     // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalGameSetting*                        CallFunc_GetGameSetting_ReturnValue;               // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APalPlayerCharacter*                    CallFunc_GetPalmi_ReturnValue;                     // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0018(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_62DB[0x7];                                     // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APalCharacter*                          CallFunc_TryGetIndividualActor_ReturnValue;        // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsDead_ReturnValue;                       // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_62DC[0x6];                                     // 0x0042(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x0048(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Vector_Distance_ReturnValue;              // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisible_ReturnValue;                    // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_DoubleDouble_ReturnValue;    // 0x0069(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x006A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_62DD[0x5];                                     // 0x006B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_GreaterEqual_DoubleDouble_A_ImplicitCast; // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BossWarningLoupe_C_IsEnableLoupe) == 0x000008, "Wrong alignment on WBP_BossWarningLoupe_C_IsEnableLoupe");
static_assert(sizeof(WBP_BossWarningLoupe_C_IsEnableLoupe) == 0x000078, "Wrong size on WBP_BossWarningLoupe_C_IsEnableLoupe");
static_assert(offsetof(WBP_BossWarningLoupe_C_IsEnableLoupe, ReturnValue) == 0x000000, "Member 'WBP_BossWarningLoupe_C_IsEnableLoupe::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_IsEnableLoupe, CallFunc_GetGameSetting_ReturnValue) == 0x000008, "Member 'WBP_BossWarningLoupe_C_IsEnableLoupe::CallFunc_GetGameSetting_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_IsEnableLoupe, CallFunc_GetPalmi_ReturnValue) == 0x000010, "Member 'WBP_BossWarningLoupe_C_IsEnableLoupe::CallFunc_GetPalmi_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_IsEnableLoupe, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000018, "Member 'WBP_BossWarningLoupe_C_IsEnableLoupe::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_IsEnableLoupe, CallFunc_IsValid_ReturnValue) == 0x000030, "Member 'WBP_BossWarningLoupe_C_IsEnableLoupe::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_IsEnableLoupe, CallFunc_TryGetIndividualActor_ReturnValue) == 0x000038, "Member 'WBP_BossWarningLoupe_C_IsEnableLoupe::CallFunc_TryGetIndividualActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_IsEnableLoupe, CallFunc_IsValid_ReturnValue_1) == 0x000040, "Member 'WBP_BossWarningLoupe_C_IsEnableLoupe::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_IsEnableLoupe, CallFunc_IsDead_ReturnValue) == 0x000041, "Member 'WBP_BossWarningLoupe_C_IsEnableLoupe::CallFunc_IsDead_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_IsEnableLoupe, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x000048, "Member 'WBP_BossWarningLoupe_C_IsEnableLoupe::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_IsEnableLoupe, CallFunc_Vector_Distance_ReturnValue) == 0x000060, "Member 'WBP_BossWarningLoupe_C_IsEnableLoupe::CallFunc_Vector_Distance_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_IsEnableLoupe, CallFunc_IsVisible_ReturnValue) == 0x000068, "Member 'WBP_BossWarningLoupe_C_IsEnableLoupe::CallFunc_IsVisible_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_IsEnableLoupe, CallFunc_GreaterEqual_DoubleDouble_ReturnValue) == 0x000069, "Member 'WBP_BossWarningLoupe_C_IsEnableLoupe::CallFunc_GreaterEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_IsEnableLoupe, CallFunc_BooleanAND_ReturnValue) == 0x00006A, "Member 'WBP_BossWarningLoupe_C_IsEnableLoupe::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_IsEnableLoupe, CallFunc_GreaterEqual_DoubleDouble_A_ImplicitCast) == 0x000070, "Member 'WBP_BossWarningLoupe_C_IsEnableLoupe::CallFunc_GreaterEqual_DoubleDouble_A_ImplicitCast' has a wrong offset!");

// Function WBP_BossWarningLoupe.WBP_BossWarningLoupe_C.SetFinalWidgetOpacity
// 0x0010 (0x0010 - 0x0000)
struct WBP_BossWarningLoupe_C_SetFinalWidgetOpacity final
{
public:
	double                                        CalcedOpacity;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetRenderOpacity_InOpacity_ImplicitCast;  // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BossWarningLoupe_C_SetFinalWidgetOpacity) == 0x000008, "Wrong alignment on WBP_BossWarningLoupe_C_SetFinalWidgetOpacity");
static_assert(sizeof(WBP_BossWarningLoupe_C_SetFinalWidgetOpacity) == 0x000010, "Wrong size on WBP_BossWarningLoupe_C_SetFinalWidgetOpacity");
static_assert(offsetof(WBP_BossWarningLoupe_C_SetFinalWidgetOpacity, CalcedOpacity) == 0x000000, "Member 'WBP_BossWarningLoupe_C_SetFinalWidgetOpacity::CalcedOpacity' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_SetFinalWidgetOpacity, CallFunc_SetRenderOpacity_InOpacity_ImplicitCast) == 0x000008, "Member 'WBP_BossWarningLoupe_C_SetFinalWidgetOpacity::CallFunc_SetRenderOpacity_InOpacity_ImplicitCast' has a wrong offset!");

// Function WBP_BossWarningLoupe.WBP_BossWarningLoupe_C.Setup
// 0x0008 (0x0008 - 0x0000)
struct WBP_BossWarningLoupe_C_Setup final
{
public:
	class UPalIndividualCharacterHandle*          Param_TargetHandle;                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BossWarningLoupe_C_Setup) == 0x000008, "Wrong alignment on WBP_BossWarningLoupe_C_Setup");
static_assert(sizeof(WBP_BossWarningLoupe_C_Setup) == 0x000008, "Wrong size on WBP_BossWarningLoupe_C_Setup");
static_assert(offsetof(WBP_BossWarningLoupe_C_Setup, Param_TargetHandle) == 0x000000, "Member 'WBP_BossWarningLoupe_C_Setup::Param_TargetHandle' has a wrong offset!");

// Function WBP_BossWarningLoupe.WBP_BossWarningLoupe_C.UpdateArrowImageAngle
// 0x0010 (0x0010 - 0x0000)
struct WBP_BossWarningLoupe_C_UpdateArrowImageAngle final
{
public:
	double                                        NewAngle;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetRenderTransformAngle_Angle_ImplicitCast; // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BossWarningLoupe_C_UpdateArrowImageAngle) == 0x000008, "Wrong alignment on WBP_BossWarningLoupe_C_UpdateArrowImageAngle");
static_assert(sizeof(WBP_BossWarningLoupe_C_UpdateArrowImageAngle) == 0x000010, "Wrong size on WBP_BossWarningLoupe_C_UpdateArrowImageAngle");
static_assert(offsetof(WBP_BossWarningLoupe_C_UpdateArrowImageAngle, NewAngle) == 0x000000, "Member 'WBP_BossWarningLoupe_C_UpdateArrowImageAngle::NewAngle' has a wrong offset!");
static_assert(offsetof(WBP_BossWarningLoupe_C_UpdateArrowImageAngle, CallFunc_SetRenderTransformAngle_Angle_ImplicitCast) == 0x000008, "Member 'WBP_BossWarningLoupe_C_UpdateArrowImageAngle::CallFunc_SetRenderTransformAngle_Angle_ImplicitCast' has a wrong offset!");

}

