#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DemoOP_TerminalScreen

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_DemoOP_TerminalScreen.WBP_DemoOP_TerminalScreen_C
// 0x0050 (0x02C8 - 0x0278)
class UWBP_DemoOP_TerminalScreen_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Anim_Text;                                         // 0x0280(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anim_Start;                                        // 0x0288(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Image_Base;                                        // 0x0290(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Base_1;                                      // 0x0298(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_BlurCircle;                                  // 0x02A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Pattern_Dot;                                 // 0x02A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Pattern_Grid;                                // 0x02B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Symbol;                                      // 0x02B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UPalRetainerBox*                        PalRetainerBox_Glitch;                             // 0x02C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void AnmEvent_Boot();
	void AnmEvent_Reset();
	void AnmEvent_Text_Seq1();
	void ExecuteUbergraph_WBP_DemoOP_TerminalScreen(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_DemoOP_TerminalScreen_C">();
	}
	static class UWBP_DemoOP_TerminalScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_DemoOP_TerminalScreen_C>();
	}
};
static_assert(alignof(UWBP_DemoOP_TerminalScreen_C) == 0x000008, "Wrong alignment on UWBP_DemoOP_TerminalScreen_C");
static_assert(sizeof(UWBP_DemoOP_TerminalScreen_C) == 0x0002C8, "Wrong size on UWBP_DemoOP_TerminalScreen_C");
static_assert(offsetof(UWBP_DemoOP_TerminalScreen_C, UberGraphFrame) == 0x000278, "Member 'UWBP_DemoOP_TerminalScreen_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_DemoOP_TerminalScreen_C, Anim_Text) == 0x000280, "Member 'UWBP_DemoOP_TerminalScreen_C::Anim_Text' has a wrong offset!");
static_assert(offsetof(UWBP_DemoOP_TerminalScreen_C, Anim_Start) == 0x000288, "Member 'UWBP_DemoOP_TerminalScreen_C::Anim_Start' has a wrong offset!");
static_assert(offsetof(UWBP_DemoOP_TerminalScreen_C, Image_Base) == 0x000290, "Member 'UWBP_DemoOP_TerminalScreen_C::Image_Base' has a wrong offset!");
static_assert(offsetof(UWBP_DemoOP_TerminalScreen_C, Image_Base_1) == 0x000298, "Member 'UWBP_DemoOP_TerminalScreen_C::Image_Base_1' has a wrong offset!");
static_assert(offsetof(UWBP_DemoOP_TerminalScreen_C, Image_BlurCircle) == 0x0002A0, "Member 'UWBP_DemoOP_TerminalScreen_C::Image_BlurCircle' has a wrong offset!");
static_assert(offsetof(UWBP_DemoOP_TerminalScreen_C, Image_Pattern_Dot) == 0x0002A8, "Member 'UWBP_DemoOP_TerminalScreen_C::Image_Pattern_Dot' has a wrong offset!");
static_assert(offsetof(UWBP_DemoOP_TerminalScreen_C, Image_Pattern_Grid) == 0x0002B0, "Member 'UWBP_DemoOP_TerminalScreen_C::Image_Pattern_Grid' has a wrong offset!");
static_assert(offsetof(UWBP_DemoOP_TerminalScreen_C, Image_Symbol) == 0x0002B8, "Member 'UWBP_DemoOP_TerminalScreen_C::Image_Symbol' has a wrong offset!");
static_assert(offsetof(UWBP_DemoOP_TerminalScreen_C, PalRetainerBox_Glitch) == 0x0002C0, "Member 'UWBP_DemoOP_TerminalScreen_C::PalRetainerBox_Glitch' has a wrong offset!");

}

