#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BoxPalList

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function WBP_BoxPalList.WBP_BoxPalList_C.BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_0_OnLeftClickedSlot__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_0_OnLeftClickedSlot__DelegateSignature final
{
public:
	class UWBP_PalCharacterSlotButtonBase_C*      Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	EPalItemSlotPressType                         PressType;                                         // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_0_OnLeftClickedSlot__DelegateSignature) == 0x000008, "Wrong alignment on WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_0_OnLeftClickedSlot__DelegateSignature");
static_assert(sizeof(WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_0_OnLeftClickedSlot__DelegateSignature) == 0x000010, "Wrong size on WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_0_OnLeftClickedSlot__DelegateSignature");
static_assert(offsetof(WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_0_OnLeftClickedSlot__DelegateSignature, Widget) == 0x000000, "Member 'WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_0_OnLeftClickedSlot__DelegateSignature::Widget' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_0_OnLeftClickedSlot__DelegateSignature, PressType) == 0x000008, "Member 'WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_0_OnLeftClickedSlot__DelegateSignature::PressType' has a wrong offset!");

// Function WBP_BoxPalList.WBP_BoxPalList_C.BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_1_OnRightClickedSlot__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_1_OnRightClickedSlot__DelegateSignature final
{
public:
	class UWBP_PalCharacterSlotButtonBase_C*      Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_1_OnRightClickedSlot__DelegateSignature) == 0x000008, "Wrong alignment on WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_1_OnRightClickedSlot__DelegateSignature");
static_assert(sizeof(WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_1_OnRightClickedSlot__DelegateSignature) == 0x000008, "Wrong size on WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_1_OnRightClickedSlot__DelegateSignature");
static_assert(offsetof(WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_1_OnRightClickedSlot__DelegateSignature, Widget) == 0x000000, "Member 'WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_1_OnRightClickedSlot__DelegateSignature::Widget' has a wrong offset!");

// Function WBP_BoxPalList.WBP_BoxPalList_C.BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_2_OnHoveredSlot__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_2_OnHoveredSlot__DelegateSignature final
{
public:
	class UWBP_PalCharacterSlotButtonBase_C*      Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_2_OnHoveredSlot__DelegateSignature) == 0x000008, "Wrong alignment on WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_2_OnHoveredSlot__DelegateSignature");
static_assert(sizeof(WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_2_OnHoveredSlot__DelegateSignature) == 0x000008, "Wrong size on WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_2_OnHoveredSlot__DelegateSignature");
static_assert(offsetof(WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_2_OnHoveredSlot__DelegateSignature, Widget) == 0x000000, "Member 'WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_2_OnHoveredSlot__DelegateSignature::Widget' has a wrong offset!");

// Function WBP_BoxPalList.WBP_BoxPalList_C.BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_3_OnUnhoveredSlot__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_3_OnUnhoveredSlot__DelegateSignature final
{
public:
	class UWBP_PalCharacterSlotButtonBase_C*      Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_3_OnUnhoveredSlot__DelegateSignature) == 0x000008, "Wrong alignment on WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_3_OnUnhoveredSlot__DelegateSignature");
static_assert(sizeof(WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_3_OnUnhoveredSlot__DelegateSignature) == 0x000008, "Wrong size on WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_3_OnUnhoveredSlot__DelegateSignature");
static_assert(offsetof(WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_3_OnUnhoveredSlot__DelegateSignature, Widget) == 0x000000, "Member 'WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_3_OnUnhoveredSlot__DelegateSignature::Widget' has a wrong offset!");

// Function WBP_BoxPalList.WBP_BoxPalList_C.BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_4_OnCreatedSlot__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_4_OnCreatedSlot__DelegateSignature final
{
public:
	class UWBP_PalCharacterSlotButtonBase_C*      CreatedSlot;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_4_OnCreatedSlot__DelegateSignature) == 0x000008, "Wrong alignment on WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_4_OnCreatedSlot__DelegateSignature");
static_assert(sizeof(WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_4_OnCreatedSlot__DelegateSignature) == 0x000008, "Wrong size on WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_4_OnCreatedSlot__DelegateSignature");
static_assert(offsetof(WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_4_OnCreatedSlot__DelegateSignature, CreatedSlot) == 0x000000, "Member 'WBP_BoxPalList_C_BndEvt__WBP_BoxPalList_WBP_BoxPalScrollList_K2Node_ComponentBoundEvent_4_OnCreatedSlot__DelegateSignature::CreatedSlot' has a wrong offset!");

// Function WBP_BoxPalList.WBP_BoxPalList_C.ExecuteUbergraph_WBP_BoxPalList
// 0x00D0 (0x00D0 - 0x0000)
struct WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_nowPage;                              // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UPalIndividualCharacterSlot*>    K2Node_Event_slotList;                             // 0x0008(0x0010)(ConstParm, ReferenceParm)
	class UWBP_PalCharacterSlotButtonBase_C*      K2Node_ComponentBoundEvent_Widget;                 // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_PalCharacterSlotButtonBase_C*      K2Node_ComponentBoundEvent_createdSlot;            // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_PalCharacterSlotButtonBase_C*      K2Node_ComponentBoundEvent_Widget_1;               // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_PalCommonCharacterSlotButton_C*    K2Node_DynamicCast_AsWBP_Pal_Common_Character_Slot_Button; // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3FA2[0x7];                                     // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalIndividualCharacterSlot*            CallFunc_GetTargetSlot_targetSlot;                 // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWBP_PalCharacterSlotButtonBase_C*      K2Node_ComponentBoundEvent_Widget_2;               // 0x0048(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_PalCharacterSlotButtonBase_C*      K2Node_ComponentBoundEvent_Widget_3;               // 0x0050(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	EPalItemSlotPressType                         K2Node_ComponentBoundEvent_PressType;              // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3FA3[0x7];                                     // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalPlayerDataStorage*                  CallFunc_GetPlayerDataStorage_ReturnValue;         // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalPlayerDataPalStorage*               CallFunc_GetPalStorage_ReturnValue;                // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetValue_ReturnValue;                     // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetPageNum_ReturnValue;                   // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_IntToDouble_ReturnValue;             // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3FA4[0x4];                                     // 0x0084(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Round_ReturnValue;                        // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Min_ReturnValue;                          // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0098(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x00A8(0x0008)(NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x00B0(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue_1;        // 0x00C0(0x0008)(NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast;     // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList) == 0x000008, "Wrong alignment on WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList");
static_assert(sizeof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList) == 0x0000D0, "Wrong size on WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, EntryPoint) == 0x000000, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, K2Node_Event_nowPage) == 0x000004, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::K2Node_Event_nowPage' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, K2Node_Event_slotList) == 0x000008, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::K2Node_Event_slotList' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, K2Node_ComponentBoundEvent_Widget) == 0x000018, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::K2Node_ComponentBoundEvent_Widget' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, K2Node_ComponentBoundEvent_createdSlot) == 0x000020, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::K2Node_ComponentBoundEvent_createdSlot' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, K2Node_ComponentBoundEvent_Widget_1) == 0x000028, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::K2Node_ComponentBoundEvent_Widget_1' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, K2Node_DynamicCast_AsWBP_Pal_Common_Character_Slot_Button) == 0x000030, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::K2Node_DynamicCast_AsWBP_Pal_Common_Character_Slot_Button' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, K2Node_DynamicCast_bSuccess) == 0x000038, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, CallFunc_GetTargetSlot_targetSlot) == 0x000040, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::CallFunc_GetTargetSlot_targetSlot' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, K2Node_ComponentBoundEvent_Widget_2) == 0x000048, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::K2Node_ComponentBoundEvent_Widget_2' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, K2Node_ComponentBoundEvent_Widget_3) == 0x000050, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::K2Node_ComponentBoundEvent_Widget_3' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, K2Node_ComponentBoundEvent_PressType) == 0x000058, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::K2Node_ComponentBoundEvent_PressType' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, CallFunc_GetPlayerDataStorage_ReturnValue) == 0x000060, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::CallFunc_GetPlayerDataStorage_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, CallFunc_GetPalStorage_ReturnValue) == 0x000068, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::CallFunc_GetPalStorage_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, CallFunc_GetValue_ReturnValue) == 0x000070, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::CallFunc_GetValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, CallFunc_GetPageNum_ReturnValue) == 0x000074, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::CallFunc_GetPageNum_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, CallFunc_Conv_IntToDouble_ReturnValue) == 0x000078, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::CallFunc_Conv_IntToDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, CallFunc_Subtract_IntInt_ReturnValue) == 0x000080, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000088, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, CallFunc_Round_ReturnValue) == 0x000090, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::CallFunc_Round_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, CallFunc_Min_ReturnValue) == 0x000094, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::CallFunc_Min_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, K2Node_CreateDelegate_OutputDelegate) == 0x000098, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x0000A8, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, K2Node_CreateDelegate_OutputDelegate_1) == 0x0000B0, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, CallFunc_K2_SetTimerDelegate_ReturnValue_1) == 0x0000C0, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::CallFunc_K2_SetTimerDelegate_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList, CallFunc_Multiply_DoubleDouble_A_ImplicitCast) == 0x0000C8, "Member 'WBP_BoxPalList_C_ExecuteUbergraph_WBP_BoxPalList::CallFunc_Multiply_DoubleDouble_A_ImplicitCast' has a wrong offset!");

// Function WBP_BoxPalList.WBP_BoxPalList_C.FindWidgetBySlot
// 0x0020 (0x0020 - 0x0000)
struct WBP_BoxPalList_C_FindWidgetBySlot final
{
public:
	class UPalIndividualCharacterSlot*            Param_Slot;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWBP_PalCharacterSlotButtonBase_C*      Widget;                                            // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_PalCommonCharacterSlotButton_C*    CallFunc_Map_Find_Value;                           // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BoxPalList_C_FindWidgetBySlot) == 0x000008, "Wrong alignment on WBP_BoxPalList_C_FindWidgetBySlot");
static_assert(sizeof(WBP_BoxPalList_C_FindWidgetBySlot) == 0x000020, "Wrong size on WBP_BoxPalList_C_FindWidgetBySlot");
static_assert(offsetof(WBP_BoxPalList_C_FindWidgetBySlot, Param_Slot) == 0x000000, "Member 'WBP_BoxPalList_C_FindWidgetBySlot::Param_Slot' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_FindWidgetBySlot, Widget) == 0x000008, "Member 'WBP_BoxPalList_C_FindWidgetBySlot::Widget' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_FindWidgetBySlot, CallFunc_Map_Find_Value) == 0x000010, "Member 'WBP_BoxPalList_C_FindWidgetBySlot::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_FindWidgetBySlot, CallFunc_Map_Find_ReturnValue) == 0x000018, "Member 'WBP_BoxPalList_C_FindWidgetBySlot::CallFunc_Map_Find_ReturnValue' has a wrong offset!");

// Function WBP_BoxPalList.WBP_BoxPalList_C.GetCurrentBoxSlots
// 0x0020 (0x0020 - 0x0000)
struct WBP_BoxPalList_C_GetCurrentBoxSlots final
{
public:
	TArray<class UWBP_PalCommonCharacterSlotButton_C*> Slots;                                             // 0x0000(0x0010)(Parm, OutParm, ContainsInstancedReference)
	TArray<class UWBP_PalCommonCharacterSlotButton_C*> CallFunc_Map_Values_Values;                        // 0x0010(0x0010)(ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(WBP_BoxPalList_C_GetCurrentBoxSlots) == 0x000008, "Wrong alignment on WBP_BoxPalList_C_GetCurrentBoxSlots");
static_assert(sizeof(WBP_BoxPalList_C_GetCurrentBoxSlots) == 0x000020, "Wrong size on WBP_BoxPalList_C_GetCurrentBoxSlots");
static_assert(offsetof(WBP_BoxPalList_C_GetCurrentBoxSlots, Slots) == 0x000000, "Member 'WBP_BoxPalList_C_GetCurrentBoxSlots::Slots' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_GetCurrentBoxSlots, CallFunc_Map_Values_Values) == 0x000010, "Member 'WBP_BoxPalList_C_GetCurrentBoxSlots::CallFunc_Map_Values_Values' has a wrong offset!");

// Function WBP_BoxPalList.WBP_BoxPalList_C.GetNowDisplayingSlots
// 0x0068 (0x0068 - 0x0000)
struct WBP_BoxPalList_C_GetNowDisplayingSlots final
{
public:
	TArray<class UWBP_PalCharacterSlotButtonBase_C*> Slots;                                             // 0x0000(0x0010)(Parm, OutParm, ContainsInstancedReference)
	TArray<class UWBP_PalCharacterSlotButtonBase_C*> NewLocalVar;                                       // 0x0010(0x0010)(Edit, BlueprintVisible, ContainsInstancedReference)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3FA5[0x4];                                     // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWidget*>                        CallFunc_Get_All_Children_widgets;                 // 0x0030(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3FA6[0x4];                                     // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Array_Get_Item;                           // 0x0048(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3FA7[0x7];                                     // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_PalCharacterSlotButtonBase_C*      K2Node_DynamicCast_AsWBP_Pal_Character_Slot_Button_Base; // 0x0058(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3FA8[0x3];                                     // 0x0061(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BoxPalList_C_GetNowDisplayingSlots) == 0x000008, "Wrong alignment on WBP_BoxPalList_C_GetNowDisplayingSlots");
static_assert(sizeof(WBP_BoxPalList_C_GetNowDisplayingSlots) == 0x000068, "Wrong size on WBP_BoxPalList_C_GetNowDisplayingSlots");
static_assert(offsetof(WBP_BoxPalList_C_GetNowDisplayingSlots, Slots) == 0x000000, "Member 'WBP_BoxPalList_C_GetNowDisplayingSlots::Slots' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_GetNowDisplayingSlots, NewLocalVar) == 0x000010, "Member 'WBP_BoxPalList_C_GetNowDisplayingSlots::NewLocalVar' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_GetNowDisplayingSlots, Temp_int_Array_Index_Variable) == 0x000020, "Member 'WBP_BoxPalList_C_GetNowDisplayingSlots::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_GetNowDisplayingSlots, Temp_int_Loop_Counter_Variable) == 0x000024, "Member 'WBP_BoxPalList_C_GetNowDisplayingSlots::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_GetNowDisplayingSlots, CallFunc_Add_IntInt_ReturnValue) == 0x000028, "Member 'WBP_BoxPalList_C_GetNowDisplayingSlots::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_GetNowDisplayingSlots, CallFunc_Get_All_Children_widgets) == 0x000030, "Member 'WBP_BoxPalList_C_GetNowDisplayingSlots::CallFunc_Get_All_Children_widgets' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_GetNowDisplayingSlots, CallFunc_Array_Length_ReturnValue) == 0x000040, "Member 'WBP_BoxPalList_C_GetNowDisplayingSlots::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_GetNowDisplayingSlots, CallFunc_Array_Get_Item) == 0x000048, "Member 'WBP_BoxPalList_C_GetNowDisplayingSlots::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_GetNowDisplayingSlots, CallFunc_Less_IntInt_ReturnValue) == 0x000050, "Member 'WBP_BoxPalList_C_GetNowDisplayingSlots::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_GetNowDisplayingSlots, K2Node_DynamicCast_AsWBP_Pal_Character_Slot_Button_Base) == 0x000058, "Member 'WBP_BoxPalList_C_GetNowDisplayingSlots::K2Node_DynamicCast_AsWBP_Pal_Character_Slot_Button_Base' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_GetNowDisplayingSlots, K2Node_DynamicCast_bSuccess) == 0x000060, "Member 'WBP_BoxPalList_C_GetNowDisplayingSlots::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_GetNowDisplayingSlots, CallFunc_Array_Add_ReturnValue) == 0x000064, "Member 'WBP_BoxPalList_C_GetNowDisplayingSlots::CallFunc_Array_Add_ReturnValue' has a wrong offset!");

// Function WBP_BoxPalList.WBP_BoxPalList_C.OnCreatedNewSlot__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_BoxPalList_C_OnCreatedNewSlot__DelegateSignature final
{
public:
	class UWBP_PalCharacterSlotButtonBase_C*      NewSlot;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BoxPalList_C_OnCreatedNewSlot__DelegateSignature) == 0x000008, "Wrong alignment on WBP_BoxPalList_C_OnCreatedNewSlot__DelegateSignature");
static_assert(sizeof(WBP_BoxPalList_C_OnCreatedNewSlot__DelegateSignature) == 0x000008, "Wrong size on WBP_BoxPalList_C_OnCreatedNewSlot__DelegateSignature");
static_assert(offsetof(WBP_BoxPalList_C_OnCreatedNewSlot__DelegateSignature, NewSlot) == 0x000000, "Member 'WBP_BoxPalList_C_OnCreatedNewSlot__DelegateSignature::NewSlot' has a wrong offset!");

// Function WBP_BoxPalList.WBP_BoxPalList_C.OnHoveredSlot__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_BoxPalList_C_OnHoveredSlot__DelegateSignature final
{
public:
	class UWBP_PalCharacterSlotButtonBase_C*      Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BoxPalList_C_OnHoveredSlot__DelegateSignature) == 0x000008, "Wrong alignment on WBP_BoxPalList_C_OnHoveredSlot__DelegateSignature");
static_assert(sizeof(WBP_BoxPalList_C_OnHoveredSlot__DelegateSignature) == 0x000008, "Wrong size on WBP_BoxPalList_C_OnHoveredSlot__DelegateSignature");
static_assert(offsetof(WBP_BoxPalList_C_OnHoveredSlot__DelegateSignature, Widget) == 0x000000, "Member 'WBP_BoxPalList_C_OnHoveredSlot__DelegateSignature::Widget' has a wrong offset!");

// Function WBP_BoxPalList.WBP_BoxPalList_C.OnLeftClickedSlot__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct WBP_BoxPalList_C_OnLeftClickedSlot__DelegateSignature final
{
public:
	class UWBP_PalCharacterSlotButtonBase_C*      Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	EPalItemSlotPressType                         PressType;                                         // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BoxPalList_C_OnLeftClickedSlot__DelegateSignature) == 0x000008, "Wrong alignment on WBP_BoxPalList_C_OnLeftClickedSlot__DelegateSignature");
static_assert(sizeof(WBP_BoxPalList_C_OnLeftClickedSlot__DelegateSignature) == 0x000010, "Wrong size on WBP_BoxPalList_C_OnLeftClickedSlot__DelegateSignature");
static_assert(offsetof(WBP_BoxPalList_C_OnLeftClickedSlot__DelegateSignature, Widget) == 0x000000, "Member 'WBP_BoxPalList_C_OnLeftClickedSlot__DelegateSignature::Widget' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_OnLeftClickedSlot__DelegateSignature, PressType) == 0x000008, "Member 'WBP_BoxPalList_C_OnLeftClickedSlot__DelegateSignature::PressType' has a wrong offset!");

// Function WBP_BoxPalList.WBP_BoxPalList_C.OnRightClickedSlot__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_BoxPalList_C_OnRightClickedSlot__DelegateSignature final
{
public:
	class UWBP_PalCharacterSlotButtonBase_C*      Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BoxPalList_C_OnRightClickedSlot__DelegateSignature) == 0x000008, "Wrong alignment on WBP_BoxPalList_C_OnRightClickedSlot__DelegateSignature");
static_assert(sizeof(WBP_BoxPalList_C_OnRightClickedSlot__DelegateSignature) == 0x000008, "Wrong size on WBP_BoxPalList_C_OnRightClickedSlot__DelegateSignature");
static_assert(offsetof(WBP_BoxPalList_C_OnRightClickedSlot__DelegateSignature, Widget) == 0x000000, "Member 'WBP_BoxPalList_C_OnRightClickedSlot__DelegateSignature::Widget' has a wrong offset!");

// Function WBP_BoxPalList.WBP_BoxPalList_C.OnSelectPalBoxPage__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct WBP_BoxPalList_C_OnSelectPalBoxPage__DelegateSignature final
{
public:
	int32                                         Page;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BoxPalList_C_OnSelectPalBoxPage__DelegateSignature) == 0x000004, "Wrong alignment on WBP_BoxPalList_C_OnSelectPalBoxPage__DelegateSignature");
static_assert(sizeof(WBP_BoxPalList_C_OnSelectPalBoxPage__DelegateSignature) == 0x000004, "Wrong size on WBP_BoxPalList_C_OnSelectPalBoxPage__DelegateSignature");
static_assert(offsetof(WBP_BoxPalList_C_OnSelectPalBoxPage__DelegateSignature, Page) == 0x000000, "Member 'WBP_BoxPalList_C_OnSelectPalBoxPage__DelegateSignature::Page' has a wrong offset!");

// Function WBP_BoxPalList.WBP_BoxPalList_C.OnUnhoveredSlot__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_BoxPalList_C_OnUnhoveredSlot__DelegateSignature final
{
public:
	class UWBP_PalCharacterSlotButtonBase_C*      Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BoxPalList_C_OnUnhoveredSlot__DelegateSignature) == 0x000008, "Wrong alignment on WBP_BoxPalList_C_OnUnhoveredSlot__DelegateSignature");
static_assert(sizeof(WBP_BoxPalList_C_OnUnhoveredSlot__DelegateSignature) == 0x000008, "Wrong size on WBP_BoxPalList_C_OnUnhoveredSlot__DelegateSignature");
static_assert(offsetof(WBP_BoxPalList_C_OnUnhoveredSlot__DelegateSignature, Widget) == 0x000000, "Member 'WBP_BoxPalList_C_OnUnhoveredSlot__DelegateSignature::Widget' has a wrong offset!");

// Function WBP_BoxPalList.WBP_BoxPalList_C.OnUpdatedPage__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct WBP_BoxPalList_C_OnUpdatedPage__DelegateSignature final
{
public:
	int32                                         NowPage;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BoxPalList_C_OnUpdatedPage__DelegateSignature) == 0x000004, "Wrong alignment on WBP_BoxPalList_C_OnUpdatedPage__DelegateSignature");
static_assert(sizeof(WBP_BoxPalList_C_OnUpdatedPage__DelegateSignature) == 0x000004, "Wrong size on WBP_BoxPalList_C_OnUpdatedPage__DelegateSignature");
static_assert(offsetof(WBP_BoxPalList_C_OnUpdatedPage__DelegateSignature, NowPage) == 0x000000, "Member 'WBP_BoxPalList_C_OnUpdatedPage__DelegateSignature::NowPage' has a wrong offset!");

// Function WBP_BoxPalList.WBP_BoxPalList_C.OnUpdatePagePalBoxList
// 0x0018 (0x0018 - 0x0000)
struct WBP_BoxPalList_C_OnUpdatePagePalBoxList final
{
public:
	int32                                         NowPage;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3FA9[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UPalIndividualCharacterSlot*>    SlotList;                                          // 0x0008(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(WBP_BoxPalList_C_OnUpdatePagePalBoxList) == 0x000008, "Wrong alignment on WBP_BoxPalList_C_OnUpdatePagePalBoxList");
static_assert(sizeof(WBP_BoxPalList_C_OnUpdatePagePalBoxList) == 0x000018, "Wrong size on WBP_BoxPalList_C_OnUpdatePagePalBoxList");
static_assert(offsetof(WBP_BoxPalList_C_OnUpdatePagePalBoxList, NowPage) == 0x000000, "Member 'WBP_BoxPalList_C_OnUpdatePagePalBoxList::NowPage' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_OnUpdatePagePalBoxList, SlotList) == 0x000008, "Member 'WBP_BoxPalList_C_OnUpdatePagePalBoxList::SlotList' has a wrong offset!");

// Function WBP_BoxPalList.WBP_BoxPalList_C.SetCurrentPalBoxPageNum
// 0x00F8 (0x00F8 - 0x0000)
struct WBP_BoxPalList_C_SetCurrentPalBoxPageNum final
{
public:
	int32                                         PageNum;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3FAA[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Conv_IntToDouble_ReturnValue;             // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3FAB[0x4];                                     // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalPlayerDataStorage*                  CallFunc_GetPlayerDataStorage_ReturnValue;         // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int64                                         CallFunc_Conv_IntToInt64_ReturnValue;              // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPalPlayerDataPalStorage*               CallFunc_GetPalStorage_ReturnValue;                // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0030(0x0050)(HasGetValueTypeHash)
	int32                                         CallFunc_GetPageNum_ReturnValue;                   // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3FAC[0x4];                                     // 0x0084(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0088(0x0010)(ReferenceParm)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3FAD[0x4];                                     // 0x009C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Conv_IntToDouble_ReturnValue_1;           // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_IngameMenu_PalBox_PageControl_C*   CallFunc_Array_Get_Item;                           // 0x00B0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetLocalizedTextFromHandle_Text;          // 0x00B8(0x0018)()
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00D0(0x0018)()
	class UWBP_IngameMenu_PalBox_PageControl_C*   CallFunc_Array_Get_Item_1;                         // 0x00E8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetValue_InValue_ImplicitCast;            // 0x00F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BoxPalList_C_SetCurrentPalBoxPageNum) == 0x000008, "Wrong alignment on WBP_BoxPalList_C_SetCurrentPalBoxPageNum");
static_assert(sizeof(WBP_BoxPalList_C_SetCurrentPalBoxPageNum) == 0x0000F8, "Wrong size on WBP_BoxPalList_C_SetCurrentPalBoxPageNum");
static_assert(offsetof(WBP_BoxPalList_C_SetCurrentPalBoxPageNum, PageNum) == 0x000000, "Member 'WBP_BoxPalList_C_SetCurrentPalBoxPageNum::PageNum' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_SetCurrentPalBoxPageNum, CallFunc_Conv_IntToDouble_ReturnValue) == 0x000008, "Member 'WBP_BoxPalList_C_SetCurrentPalBoxPageNum::CallFunc_Conv_IntToDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_SetCurrentPalBoxPageNum, CallFunc_Add_IntInt_ReturnValue) == 0x000010, "Member 'WBP_BoxPalList_C_SetCurrentPalBoxPageNum::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_SetCurrentPalBoxPageNum, CallFunc_GetPlayerDataStorage_ReturnValue) == 0x000018, "Member 'WBP_BoxPalList_C_SetCurrentPalBoxPageNum::CallFunc_GetPlayerDataStorage_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_SetCurrentPalBoxPageNum, CallFunc_Conv_IntToInt64_ReturnValue) == 0x000020, "Member 'WBP_BoxPalList_C_SetCurrentPalBoxPageNum::CallFunc_Conv_IntToInt64_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_SetCurrentPalBoxPageNum, CallFunc_GetPalStorage_ReturnValue) == 0x000028, "Member 'WBP_BoxPalList_C_SetCurrentPalBoxPageNum::CallFunc_GetPalStorage_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_SetCurrentPalBoxPageNum, K2Node_MakeStruct_FormatArgumentData) == 0x000030, "Member 'WBP_BoxPalList_C_SetCurrentPalBoxPageNum::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_SetCurrentPalBoxPageNum, CallFunc_GetPageNum_ReturnValue) == 0x000080, "Member 'WBP_BoxPalList_C_SetCurrentPalBoxPageNum::CallFunc_GetPageNum_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_SetCurrentPalBoxPageNum, K2Node_MakeArray_Array) == 0x000088, "Member 'WBP_BoxPalList_C_SetCurrentPalBoxPageNum::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_SetCurrentPalBoxPageNum, CallFunc_Subtract_IntInt_ReturnValue) == 0x000098, "Member 'WBP_BoxPalList_C_SetCurrentPalBoxPageNum::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_SetCurrentPalBoxPageNum, CallFunc_Conv_IntToDouble_ReturnValue_1) == 0x0000A0, "Member 'WBP_BoxPalList_C_SetCurrentPalBoxPageNum::CallFunc_Conv_IntToDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_SetCurrentPalBoxPageNum, CallFunc_Divide_DoubleDouble_ReturnValue) == 0x0000A8, "Member 'WBP_BoxPalList_C_SetCurrentPalBoxPageNum::CallFunc_Divide_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_SetCurrentPalBoxPageNum, CallFunc_Array_Get_Item) == 0x0000B0, "Member 'WBP_BoxPalList_C_SetCurrentPalBoxPageNum::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_SetCurrentPalBoxPageNum, CallFunc_GetLocalizedTextFromHandle_Text) == 0x0000B8, "Member 'WBP_BoxPalList_C_SetCurrentPalBoxPageNum::CallFunc_GetLocalizedTextFromHandle_Text' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_SetCurrentPalBoxPageNum, CallFunc_Format_ReturnValue) == 0x0000D0, "Member 'WBP_BoxPalList_C_SetCurrentPalBoxPageNum::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_SetCurrentPalBoxPageNum, CallFunc_Array_Get_Item_1) == 0x0000E8, "Member 'WBP_BoxPalList_C_SetCurrentPalBoxPageNum::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_SetCurrentPalBoxPageNum, CallFunc_SetValue_InValue_ImplicitCast) == 0x0000F0, "Member 'WBP_BoxPalList_C_SetCurrentPalBoxPageNum::CallFunc_SetValue_InValue_ImplicitCast' has a wrong offset!");

// Function WBP_BoxPalList.WBP_BoxPalList_C.Setup
// 0x0090 (0x0090 - 0x0000)
struct WBP_BoxPalList_C_Setup final
{
public:
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0000(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0010(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FPalUIActionBindData                   CallFunc_RegisterActionBinding_ReturnValue;        // 0x0020(0x0004)(NoDestructor)
	struct FPalUIActionBindData                   CallFunc_RegisterActionBinding_ReturnValue_1;      // 0x0024(0x0004)(NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0028(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FPalUIActionBindData                   CallFunc_RegisterActionBinding_ReturnValue_2;      // 0x0038(0x0004)(NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x003C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FPalUIActionBindData                   CallFunc_RegisterActionBinding_ReturnValue_3;      // 0x004C(0x0004)(NoDestructor)
	struct FSlateChildSize                        K2Node_MakeStruct_SlateChildSize;                  // 0x0050(0x0008)(NoDestructor)
	class APlayerController*                      CallFunc_GetLocalPlayerController_ReturnValue;     // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3FAE[0x4];                                     // 0x0064(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_IngameMenu_PalBox_PageControl_C*   CallFunc_SpawnObject_ReturnValue;                  // 0x0068(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3FAF[0x4];                                     // 0x0074(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UHorizontalBoxSlot*                     CallFunc_AddChildToHorizontalBox_ReturnValue;      // 0x0078(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetBoxMaxPageNum_ReturnValue;             // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BoxPalList_C_Setup) == 0x000008, "Wrong alignment on WBP_BoxPalList_C_Setup");
static_assert(sizeof(WBP_BoxPalList_C_Setup) == 0x000090, "Wrong size on WBP_BoxPalList_C_Setup");
static_assert(offsetof(WBP_BoxPalList_C_Setup, K2Node_CreateDelegate_OutputDelegate) == 0x000000, "Member 'WBP_BoxPalList_C_Setup::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_Setup, K2Node_CreateDelegate_OutputDelegate_1) == 0x000010, "Member 'WBP_BoxPalList_C_Setup::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_Setup, CallFunc_RegisterActionBinding_ReturnValue) == 0x000020, "Member 'WBP_BoxPalList_C_Setup::CallFunc_RegisterActionBinding_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_Setup, CallFunc_RegisterActionBinding_ReturnValue_1) == 0x000024, "Member 'WBP_BoxPalList_C_Setup::CallFunc_RegisterActionBinding_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_Setup, K2Node_CreateDelegate_OutputDelegate_2) == 0x000028, "Member 'WBP_BoxPalList_C_Setup::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_Setup, CallFunc_RegisterActionBinding_ReturnValue_2) == 0x000038, "Member 'WBP_BoxPalList_C_Setup::CallFunc_RegisterActionBinding_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_Setup, K2Node_CreateDelegate_OutputDelegate_3) == 0x00003C, "Member 'WBP_BoxPalList_C_Setup::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_Setup, CallFunc_RegisterActionBinding_ReturnValue_3) == 0x00004C, "Member 'WBP_BoxPalList_C_Setup::CallFunc_RegisterActionBinding_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_Setup, K2Node_MakeStruct_SlateChildSize) == 0x000050, "Member 'WBP_BoxPalList_C_Setup::K2Node_MakeStruct_SlateChildSize' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_Setup, CallFunc_GetLocalPlayerController_ReturnValue) == 0x000058, "Member 'WBP_BoxPalList_C_Setup::CallFunc_GetLocalPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_Setup, Temp_int_Variable) == 0x000060, "Member 'WBP_BoxPalList_C_Setup::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_Setup, CallFunc_SpawnObject_ReturnValue) == 0x000068, "Member 'WBP_BoxPalList_C_Setup::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_Setup, CallFunc_Array_Add_ReturnValue) == 0x000070, "Member 'WBP_BoxPalList_C_Setup::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_Setup, CallFunc_AddChildToHorizontalBox_ReturnValue) == 0x000078, "Member 'WBP_BoxPalList_C_Setup::CallFunc_AddChildToHorizontalBox_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_Setup, CallFunc_Add_IntInt_ReturnValue) == 0x000080, "Member 'WBP_BoxPalList_C_Setup::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_Setup, CallFunc_GetBoxMaxPageNum_ReturnValue) == 0x000084, "Member 'WBP_BoxPalList_C_Setup::CallFunc_GetBoxMaxPageNum_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_BoxPalList_C_Setup, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000088, "Member 'WBP_BoxPalList_C_Setup::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");

}

