#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PalNPCHPGauge

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "WBP_IndividualParameterBindWidget_classes.hpp"
#include "Pal_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_PalNPCHPGauge.WBP_PalNPCHPGauge_C
// 0x00B8 (0x0690 - 0x05D8)
class UWBP_PalNPCHPGauge_C final : public UWBP_IndividualParameterBindWidget_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_WBP_PalNPCHPGauge_C;                // 0x05D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Default_In;                                        // 0x05E0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanel*                           Canvas_Innner;                                     // 0x05E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_EnemyGauge_C*                      WBP_EnemyGauge;                                    // 0x05F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FTimerHandle                           CheckFriendTimerHandle;                            // 0x05F8(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CheckActorTimerHandle;                             // 0x0600(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	float                                         ImportedSphereRadius;                              // 0x0608(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5864[0x4];                                     // 0x060C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              DrawOffset;                                        // 0x0610(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ChachedFriendFlag;                                 // 0x0620(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          OldFriendFlag;                                     // 0x0621(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ChachedIsDead;                                     // 0x0622(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CachedBattleMode;                                  // 0x0623(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CachedRarePalFlag;                                 // 0x0624(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5865[0x3];                                     // 0x0625(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalFlyMeshHeightCtrlComponent*         FlyComponent;                                      // 0x0628(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_             OnDelayClose;                                      // 0x0630(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMap<int32, int32>                            FontSizeMap;                                       // 0x0640(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance)

public:
	void BindFromHandle(class UPalIndividualCharacterHandle* TargetHandle);
	void Construct();
	void DelayClose();
	void Destruct();
	void ExecuteUbergraph_WBP_PalNPCHPGauge(int32 EntryPoint);
	void InitializeDetail();
	void IsDead(bool* Param_IsDead);
	void IsFriend(bool* Param_IsFriend);
	void IsOtomo(bool* Param_IsOtomo);
	void On_Update_Level_Binded(int32 NewLevel);
	void On_Update_Sanity_Binded(double NowSanity, double NowMaxSanity);
	void OnBattleModeChanged(bool bIsBattleMode);
	void OnDead(const struct FPalDeadInfo& DeadInfo);
	void OnDelayClose__DelegateSignature(class UWidget* Widget);
	void OnInitialized();
	void OnTakeDamage(const struct FPalDamageResult& DamageResult);
	void OnTimer_CheckActor();
	void OnUISettingaChanged(const struct FPalOptionUISettings& PrevSettings, const struct FPalOptionUISettings& NewSettings);
	void OnUpdateCondition_Binded();
	void OnUpdateHP_Binded(const struct FFixedPoint64& NowHP, const struct FFixedPoint64& NowMaxHP);
	void OnUpdateNickName_Binded(const class FString& NewNickName);
	void OnUpdateTalent_Binded();
	void Set_Work_Suitability(const TMap<EPalWorkSuitability, int32>& WorkSuitabilities);
	void SetElementType(EPalElementType Type1, EPalElementType Type2);
	void SetGender(EPalGenderType GenderType);
	void SetRank(int32 Rank);
	void SetupByActor();
	void TimerEvent_UpdateDetail();
	void Unbind();
	void Update_Gauge_Type();
	void UpdateForTick(double DeltaTime);
	void UpdateWidgetPosition();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_PalNPCHPGauge_C">();
	}
	static class UWBP_PalNPCHPGauge_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PalNPCHPGauge_C>();
	}
};
static_assert(alignof(UWBP_PalNPCHPGauge_C) == 0x000008, "Wrong alignment on UWBP_PalNPCHPGauge_C");
static_assert(sizeof(UWBP_PalNPCHPGauge_C) == 0x000690, "Wrong size on UWBP_PalNPCHPGauge_C");
static_assert(offsetof(UWBP_PalNPCHPGauge_C, UberGraphFrame_WBP_PalNPCHPGauge_C) == 0x0005D8, "Member 'UWBP_PalNPCHPGauge_C::UberGraphFrame_WBP_PalNPCHPGauge_C' has a wrong offset!");
static_assert(offsetof(UWBP_PalNPCHPGauge_C, Default_In) == 0x0005E0, "Member 'UWBP_PalNPCHPGauge_C::Default_In' has a wrong offset!");
static_assert(offsetof(UWBP_PalNPCHPGauge_C, Canvas_Innner) == 0x0005E8, "Member 'UWBP_PalNPCHPGauge_C::Canvas_Innner' has a wrong offset!");
static_assert(offsetof(UWBP_PalNPCHPGauge_C, WBP_EnemyGauge) == 0x0005F0, "Member 'UWBP_PalNPCHPGauge_C::WBP_EnemyGauge' has a wrong offset!");
static_assert(offsetof(UWBP_PalNPCHPGauge_C, CheckFriendTimerHandle) == 0x0005F8, "Member 'UWBP_PalNPCHPGauge_C::CheckFriendTimerHandle' has a wrong offset!");
static_assert(offsetof(UWBP_PalNPCHPGauge_C, CheckActorTimerHandle) == 0x000600, "Member 'UWBP_PalNPCHPGauge_C::CheckActorTimerHandle' has a wrong offset!");
static_assert(offsetof(UWBP_PalNPCHPGauge_C, ImportedSphereRadius) == 0x000608, "Member 'UWBP_PalNPCHPGauge_C::ImportedSphereRadius' has a wrong offset!");
static_assert(offsetof(UWBP_PalNPCHPGauge_C, DrawOffset) == 0x000610, "Member 'UWBP_PalNPCHPGauge_C::DrawOffset' has a wrong offset!");
static_assert(offsetof(UWBP_PalNPCHPGauge_C, ChachedFriendFlag) == 0x000620, "Member 'UWBP_PalNPCHPGauge_C::ChachedFriendFlag' has a wrong offset!");
static_assert(offsetof(UWBP_PalNPCHPGauge_C, OldFriendFlag) == 0x000621, "Member 'UWBP_PalNPCHPGauge_C::OldFriendFlag' has a wrong offset!");
static_assert(offsetof(UWBP_PalNPCHPGauge_C, ChachedIsDead) == 0x000622, "Member 'UWBP_PalNPCHPGauge_C::ChachedIsDead' has a wrong offset!");
static_assert(offsetof(UWBP_PalNPCHPGauge_C, CachedBattleMode) == 0x000623, "Member 'UWBP_PalNPCHPGauge_C::CachedBattleMode' has a wrong offset!");
static_assert(offsetof(UWBP_PalNPCHPGauge_C, CachedRarePalFlag) == 0x000624, "Member 'UWBP_PalNPCHPGauge_C::CachedRarePalFlag' has a wrong offset!");
static_assert(offsetof(UWBP_PalNPCHPGauge_C, FlyComponent) == 0x000628, "Member 'UWBP_PalNPCHPGauge_C::FlyComponent' has a wrong offset!");
static_assert(offsetof(UWBP_PalNPCHPGauge_C, OnDelayClose) == 0x000630, "Member 'UWBP_PalNPCHPGauge_C::OnDelayClose' has a wrong offset!");
static_assert(offsetof(UWBP_PalNPCHPGauge_C, FontSizeMap) == 0x000640, "Member 'UWBP_PalNPCHPGauge_C::FontSizeMap' has a wrong offset!");

}

