#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_IngameMenu_ChestManage_TakeOut

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_structs.hpp"


namespace SDK::Params
{

// Function WBP_IngameMenu_ChestManage_TakeOut.WBP_IngameMenu_ChestManage_TakeOut_C.BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Add10_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Add10_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature final
{
public:
	int32                                         Progress;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Add10_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature) == 0x000004, "Wrong alignment on WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Add10_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature");
static_assert(sizeof(WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Add10_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature) == 0x000004, "Wrong size on WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Add10_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Add10_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature, Progress) == 0x000000, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Add10_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature::Progress' has a wrong offset!");

// Function WBP_IngameMenu_ChestManage_TakeOut.WBP_IngameMenu_ChestManage_TakeOut_C.BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_NumArrow_1_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_NumArrow_1_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature final
{
public:
	int32                                         Progress;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_NumArrow_1_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature) == 0x000004, "Wrong alignment on WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_NumArrow_1_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature");
static_assert(sizeof(WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_NumArrow_1_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature) == 0x000004, "Wrong size on WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_NumArrow_1_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_NumArrow_1_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature, Progress) == 0x000000, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_NumArrow_1_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature::Progress' has a wrong offset!");

// Function WBP_IngameMenu_ChestManage_TakeOut.WBP_IngameMenu_ChestManage_TakeOut_C.BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Slider_K2Node_ComponentBoundEvent_7_OnValueChanged__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Slider_K2Node_ComponentBoundEvent_7_OnValueChanged__DelegateSignature final
{
public:
	int32                                         NewCount;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Slider_K2Node_ComponentBoundEvent_7_OnValueChanged__DelegateSignature) == 0x000004, "Wrong alignment on WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Slider_K2Node_ComponentBoundEvent_7_OnValueChanged__DelegateSignature");
static_assert(sizeof(WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Slider_K2Node_ComponentBoundEvent_7_OnValueChanged__DelegateSignature) == 0x000004, "Wrong size on WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Slider_K2Node_ComponentBoundEvent_7_OnValueChanged__DelegateSignature");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Slider_K2Node_ComponentBoundEvent_7_OnValueChanged__DelegateSignature, NewCount) == 0x000000, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Slider_K2Node_ComponentBoundEvent_7_OnValueChanged__DelegateSignature::NewCount' has a wrong offset!");

// Function WBP_IngameMenu_ChestManage_TakeOut.WBP_IngameMenu_ChestManage_TakeOut_C.BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub10_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub10_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature final
{
public:
	int32                                         Progress;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub10_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature) == 0x000004, "Wrong alignment on WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub10_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature");
static_assert(sizeof(WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub10_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature) == 0x000004, "Wrong size on WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub10_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub10_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature, Progress) == 0x000000, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub10_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature::Progress' has a wrong offset!");

// Function WBP_IngameMenu_ChestManage_TakeOut.WBP_IngameMenu_ChestManage_TakeOut_C.BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature final
{
public:
	int32                                         Progress;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature) == 0x000004, "Wrong alignment on WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature");
static_assert(sizeof(WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature) == 0x000004, "Wrong size on WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature, Progress) == 0x000000, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature::Progress' has a wrong offset!");

// Function WBP_IngameMenu_ChestManage_TakeOut.WBP_IngameMenu_ChestManage_TakeOut_C.ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut
// 0x0034 (0x0034 - 0x0000)
struct WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Max_ReturnValue;                          // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_Progress_3;             // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_Progress_2;             // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_Progress_1;             // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_Progress;               // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3CF0[0x3];                                     // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Max_ReturnValue_1;                        // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_NewCount;               // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut) == 0x000004, "Wrong alignment on WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut");
static_assert(sizeof(WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut) == 0x000034, "Wrong size on WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut, EntryPoint) == 0x000000, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut, CallFunc_Max_ReturnValue) == 0x000004, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut::CallFunc_Max_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut, K2Node_ComponentBoundEvent_Progress_3) == 0x000008, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut::K2Node_ComponentBoundEvent_Progress_3' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut, K2Node_ComponentBoundEvent_Progress_2) == 0x00000C, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut::K2Node_ComponentBoundEvent_Progress_2' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut, K2Node_ComponentBoundEvent_Progress_1) == 0x000010, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut::K2Node_ComponentBoundEvent_Progress_1' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut, K2Node_ComponentBoundEvent_Progress) == 0x000014, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut::K2Node_ComponentBoundEvent_Progress' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut, CallFunc_Add_IntInt_ReturnValue) == 0x000018, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut, CallFunc_Add_IntInt_ReturnValue_1) == 0x00001C, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut, CallFunc_Add_IntInt_ReturnValue_2) == 0x000020, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000024, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut, CallFunc_Max_ReturnValue_1) == 0x000028, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut::CallFunc_Max_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut, CallFunc_Add_IntInt_ReturnValue_3) == 0x00002C, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut, K2Node_ComponentBoundEvent_NewCount) == 0x000030, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut::K2Node_ComponentBoundEvent_NewCount' has a wrong offset!");

// Function WBP_IngameMenu_ChestManage_TakeOut.WBP_IngameMenu_ChestManage_TakeOut_C.OnTakeOutConfirmed__DelegateSignature
// 0x002C (0x002C - 0x0000)
struct WBP_IngameMenu_ChestManage_TakeOut_C_OnTakeOutConfirmed__DelegateSignature final
{
public:
	struct FPalItemId                             TakeOutId;                                         // 0x0000(0x0028)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
	int32                                         TakeOutCount;                                      // 0x0028(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_IngameMenu_ChestManage_TakeOut_C_OnTakeOutConfirmed__DelegateSignature) == 0x000004, "Wrong alignment on WBP_IngameMenu_ChestManage_TakeOut_C_OnTakeOutConfirmed__DelegateSignature");
static_assert(sizeof(WBP_IngameMenu_ChestManage_TakeOut_C_OnTakeOutConfirmed__DelegateSignature) == 0x00002C, "Wrong size on WBP_IngameMenu_ChestManage_TakeOut_C_OnTakeOutConfirmed__DelegateSignature");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_OnTakeOutConfirmed__DelegateSignature, TakeOutId) == 0x000000, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_OnTakeOutConfirmed__DelegateSignature::TakeOutId' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_OnTakeOutConfirmed__DelegateSignature, TakeOutCount) == 0x000028, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_OnTakeOutConfirmed__DelegateSignature::TakeOutCount' has a wrong offset!");

// Function WBP_IngameMenu_ChestManage_TakeOut.WBP_IngameMenu_ChestManage_TakeOut_C.Setup
// 0x0100 (0x0100 - 0x0000)
struct WBP_IngameMenu_ChestManage_TakeOut_C_Setup final
{
public:
	struct FPalItemAndNum                         ItemAndNum;                                        // 0x0000(0x002C)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	uint8                                         Pad_3CF1[0x4];                                     // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalItemIDManager*                      CallFunc_GetItemIDManager_ReturnValue;             // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FPalItemData                           CallFunc_GetItemData_ReturnValue;                  // 0x0038(0x0010)(ConstParm, NoDestructor)
	class FText                                   CallFunc_GetItemName_outName;                      // 0x0048(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0060(0x0050)(HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3CF2[0x7];                                     // 0x00B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x00B8(0x0010)(ReferenceParm)
	int32                                         CallFunc_SelectInt_ReturnValue;                    // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3CF3[0x4];                                     // 0x00CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetLocalizedText_ReturnValue;             // 0x00D0(0x0018)()
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00E8(0x0018)()
};
static_assert(alignof(WBP_IngameMenu_ChestManage_TakeOut_C_Setup) == 0x000008, "Wrong alignment on WBP_IngameMenu_ChestManage_TakeOut_C_Setup");
static_assert(sizeof(WBP_IngameMenu_ChestManage_TakeOut_C_Setup) == 0x000100, "Wrong size on WBP_IngameMenu_ChestManage_TakeOut_C_Setup");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_Setup, ItemAndNum) == 0x000000, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_Setup::ItemAndNum' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_Setup, CallFunc_GetItemIDManager_ReturnValue) == 0x000030, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_Setup::CallFunc_GetItemIDManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_Setup, CallFunc_GetItemData_ReturnValue) == 0x000038, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_Setup::CallFunc_GetItemData_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_Setup, CallFunc_GetItemName_outName) == 0x000048, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_Setup::CallFunc_GetItemName_outName' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_Setup, K2Node_MakeStruct_FormatArgumentData) == 0x000060, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_Setup::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_Setup, CallFunc_IsValid_ReturnValue) == 0x0000B0, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_Setup::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_Setup, K2Node_MakeArray_Array) == 0x0000B8, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_Setup::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_Setup, CallFunc_SelectInt_ReturnValue) == 0x0000C8, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_Setup::CallFunc_SelectInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_Setup, CallFunc_GetLocalizedText_ReturnValue) == 0x0000D0, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_Setup::CallFunc_GetLocalizedText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_Setup, CallFunc_Format_ReturnValue) == 0x0000E8, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_Setup::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function WBP_IngameMenu_ChestManage_TakeOut.WBP_IngameMenu_ChestManage_TakeOut_C.UpdateSelectCount
// 0x0018 (0x0018 - 0x0000)
struct WBP_IngameMenu_ChestManage_TakeOut_C_UpdateSelectCount final
{
public:
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0000(0x0018)()
};
static_assert(alignof(WBP_IngameMenu_ChestManage_TakeOut_C_UpdateSelectCount) == 0x000008, "Wrong alignment on WBP_IngameMenu_ChestManage_TakeOut_C_UpdateSelectCount");
static_assert(sizeof(WBP_IngameMenu_ChestManage_TakeOut_C_UpdateSelectCount) == 0x000018, "Wrong size on WBP_IngameMenu_ChestManage_TakeOut_C_UpdateSelectCount");
static_assert(offsetof(WBP_IngameMenu_ChestManage_TakeOut_C_UpdateSelectCount, CallFunc_Conv_IntToText_ReturnValue) == 0x000000, "Member 'WBP_IngameMenu_ChestManage_TakeOut_C_UpdateSelectCount::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");

}

