#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DemoOP_TerminalScreen

#include "Basic.hpp"

#include "WBP_DemoOP_TerminalScreen_classes.hpp"
#include "WBP_DemoOP_TerminalScreen_parameters.hpp"


namespace SDK
{

// Function WBP_DemoOP_TerminalScreen.WBP_DemoOP_TerminalScreen_C.AnmEvent_Boot
// (BlueprintCallable, BlueprintEvent)

void UWBP_DemoOP_TerminalScreen_C::AnmEvent_Boot()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DemoOP_TerminalScreen_C", "AnmEvent_Boot");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DemoOP_TerminalScreen.WBP_DemoOP_TerminalScreen_C.AnmEvent_Reset
// (BlueprintCallable, BlueprintEvent)

void UWBP_DemoOP_TerminalScreen_C::AnmEvent_Reset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DemoOP_TerminalScreen_C", "AnmEvent_Reset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DemoOP_TerminalScreen.WBP_DemoOP_TerminalScreen_C.AnmEvent_Text_Seq1
// (BlueprintCallable, BlueprintEvent)

void UWBP_DemoOP_TerminalScreen_C::AnmEvent_Text_Seq1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DemoOP_TerminalScreen_C", "AnmEvent_Text_Seq1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DemoOP_TerminalScreen.WBP_DemoOP_TerminalScreen_C.ExecuteUbergraph_WBP_DemoOP_TerminalScreen
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_DemoOP_TerminalScreen_C::ExecuteUbergraph_WBP_DemoOP_TerminalScreen(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DemoOP_TerminalScreen_C", "ExecuteUbergraph_WBP_DemoOP_TerminalScreen");

	Params::WBP_DemoOP_TerminalScreen_C_ExecuteUbergraph_WBP_DemoOP_TerminalScreen Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

