#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Trading_Pal

#include "Basic.hpp"

#include "WBP_Trading_Pal_classes.hpp"
#include "WBP_Trading_Pal_parameters.hpp"


namespace SDK
{

// Function WBP_Trading_Pal.WBP_Trading_Pal_C.BndEvt__WBP_Trading_Item_PalEditableTextBox_CostNum_K2Node_ComponentBoundEvent_12_OnEditableTextBoxChangedEvent__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_Trading_Pal_C::BndEvt__WBP_Trading_Item_PalEditableTextBox_CostNum_K2Node_ComponentBoundEvent_12_OnEditableTextBoxChangedEvent__DelegateSignature(const class FText& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "BndEvt__WBP_Trading_Item_PalEditableTextBox_CostNum_K2Node_ComponentBoundEvent_12_OnEditableTextBoxChangedEvent__DelegateSignature");

	Params::WBP_Trading_Pal_C_BndEvt__WBP_Trading_Item_PalEditableTextBox_CostNum_K2Node_ComponentBoundEvent_12_OnEditableTextBoxChangedEvent__DelegateSignature Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.BndEvt__WBP_Trading_Item_PalEditableTextBox_CostNum_K2Node_ComponentBoundEvent_13_OnEditableTextBoxCommittedEvent__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// ETextCommit                             CommitMethod                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::BndEvt__WBP_Trading_Item_PalEditableTextBox_CostNum_K2Node_ComponentBoundEvent_13_OnEditableTextBoxCommittedEvent__DelegateSignature(const class FText& Text, ETextCommit CommitMethod)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "BndEvt__WBP_Trading_Item_PalEditableTextBox_CostNum_K2Node_ComponentBoundEvent_13_OnEditableTextBoxCommittedEvent__DelegateSignature");

	Params::WBP_Trading_Pal_C_BndEvt__WBP_Trading_Item_PalEditableTextBox_CostNum_K2Node_ComponentBoundEvent_13_OnEditableTextBoxCommittedEvent__DelegateSignature Parms{};

	Parms.Text = std::move(Text);
	Parms.CommitMethod = CommitMethod;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.BndEvt__WBP_Trading_Pal_WBP_BoxPalList_Party_K2Node_ComponentBoundEvent_0_OnHoverSlot__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWBP_PalCharacterSlotButtonBase_C*Param_Slot                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::BndEvt__WBP_Trading_Pal_WBP_BoxPalList_Party_K2Node_ComponentBoundEvent_0_OnHoverSlot__DelegateSignature(class UWBP_PalCharacterSlotButtonBase_C* Param_Slot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "BndEvt__WBP_Trading_Pal_WBP_BoxPalList_Party_K2Node_ComponentBoundEvent_0_OnHoverSlot__DelegateSignature");

	Params::WBP_Trading_Pal_C_BndEvt__WBP_Trading_Pal_WBP_BoxPalList_Party_K2Node_ComponentBoundEvent_0_OnHoverSlot__DelegateSignature Parms{};

	Parms.Param_Slot = Param_Slot;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.BndEvt__WBP_Trading_Pal_WBP_BoxPalList_Party_K2Node_ComponentBoundEvent_1_OnUnhoverSlot__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWBP_PalCharacterSlotButtonBase_C*Param_Slot                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::BndEvt__WBP_Trading_Pal_WBP_BoxPalList_Party_K2Node_ComponentBoundEvent_1_OnUnhoverSlot__DelegateSignature(class UWBP_PalCharacterSlotButtonBase_C* Param_Slot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "BndEvt__WBP_Trading_Pal_WBP_BoxPalList_Party_K2Node_ComponentBoundEvent_1_OnUnhoverSlot__DelegateSignature");

	Params::WBP_Trading_Pal_C_BndEvt__WBP_Trading_Pal_WBP_BoxPalList_Party_K2Node_ComponentBoundEvent_1_OnUnhoverSlot__DelegateSignature Parms{};

	Parms.Param_Slot = Param_Slot;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.BndEvt__WBP_Trading_Pal_WBP_BoxPalList_Party_K2Node_ComponentBoundEvent_5_OnCreatedNewSlot__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWBP_PalCharacterSlotButtonBase_C*Param_Slot                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::BndEvt__WBP_Trading_Pal_WBP_BoxPalList_Party_K2Node_ComponentBoundEvent_5_OnCreatedNewSlot__DelegateSignature(class UWBP_PalCharacterSlotButtonBase_C* Param_Slot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "BndEvt__WBP_Trading_Pal_WBP_BoxPalList_Party_K2Node_ComponentBoundEvent_5_OnCreatedNewSlot__DelegateSignature");

	Params::WBP_Trading_Pal_C_BndEvt__WBP_Trading_Pal_WBP_BoxPalList_Party_K2Node_ComponentBoundEvent_5_OnCreatedNewSlot__DelegateSignature Parms{};

	Parms.Param_Slot = Param_Slot;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.BndEvt__WBP_Trading_Pal_WBP_BoxPalList_Party_K2Node_ComponentBoundEvent_6_OnLeftClickedSlot__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWBP_PalCharacterSlotButtonBase_C*Param_Slot                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// EPalItemSlotPressType                   PressType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::BndEvt__WBP_Trading_Pal_WBP_BoxPalList_Party_K2Node_ComponentBoundEvent_6_OnLeftClickedSlot__DelegateSignature(class UWBP_PalCharacterSlotButtonBase_C* Param_Slot, EPalItemSlotPressType PressType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "BndEvt__WBP_Trading_Pal_WBP_BoxPalList_Party_K2Node_ComponentBoundEvent_6_OnLeftClickedSlot__DelegateSignature");

	Params::WBP_Trading_Pal_C_BndEvt__WBP_Trading_Pal_WBP_BoxPalList_Party_K2Node_ComponentBoundEvent_6_OnLeftClickedSlot__DelegateSignature Parms{};

	Parms.Param_Slot = Param_Slot;
	Parms.PressType = PressType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.BndEvt__WBP_Trading_Pal_WBP_CommonButton_Cancel_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_Trading_Pal_C::BndEvt__WBP_Trading_Pal_WBP_CommonButton_Cancel_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "BndEvt__WBP_Trading_Pal_WBP_CommonButton_Cancel_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.BndEvt__WBP_Trading_Pal_WBP_CommonButton_Confirm_K2Node_ComponentBoundEvent_14_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_Trading_Pal_C::BndEvt__WBP_Trading_Pal_WBP_CommonButton_Confirm_K2Node_ComponentBoundEvent_14_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "BndEvt__WBP_Trading_Pal_WBP_CommonButton_Confirm_K2Node_ComponentBoundEvent_14_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.BndEvt__WBP_Trading_Pal_WBP_Menu_btn_K2Node_ComponentBoundEvent_2_OnButtonClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_Trading_Pal_C::BndEvt__WBP_Trading_Pal_WBP_Menu_btn_K2Node_ComponentBoundEvent_2_OnButtonClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "BndEvt__WBP_Trading_Pal_WBP_Menu_btn_K2Node_ComponentBoundEvent_2_OnButtonClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.BndEvt__WBP_Trading_Pal_WBP_PalCommonCharacterSlotButton_Edit_K2Node_ComponentBoundEvent_4_OnClickedButton__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWBP_PalCharacterSlotButtonBase_C*Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// EPalItemSlotPressType                   PressType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::BndEvt__WBP_Trading_Pal_WBP_PalCommonCharacterSlotButton_Edit_K2Node_ComponentBoundEvent_4_OnClickedButton__DelegateSignature(class UWBP_PalCharacterSlotButtonBase_C* Widget, EPalItemSlotPressType PressType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "BndEvt__WBP_Trading_Pal_WBP_PalCommonCharacterSlotButton_Edit_K2Node_ComponentBoundEvent_4_OnClickedButton__DelegateSignature");

	Params::WBP_Trading_Pal_C_BndEvt__WBP_Trading_Pal_WBP_PalCommonCharacterSlotButton_Edit_K2Node_ComponentBoundEvent_4_OnClickedButton__DelegateSignature Parms{};

	Parms.Widget = Widget;
	Parms.PressType = PressType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.BndEvt__WBP_Trading_Pal_WBP_PalCommonCharacterSlotButton_Edit_K2Node_ComponentBoundEvent_7_OnHoveredButton__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWBP_PalCharacterSlotButtonBase_C*Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::BndEvt__WBP_Trading_Pal_WBP_PalCommonCharacterSlotButton_Edit_K2Node_ComponentBoundEvent_7_OnHoveredButton__DelegateSignature(class UWBP_PalCharacterSlotButtonBase_C* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "BndEvt__WBP_Trading_Pal_WBP_PalCommonCharacterSlotButton_Edit_K2Node_ComponentBoundEvent_7_OnHoveredButton__DelegateSignature");

	Params::WBP_Trading_Pal_C_BndEvt__WBP_Trading_Pal_WBP_PalCommonCharacterSlotButton_Edit_K2Node_ComponentBoundEvent_7_OnHoveredButton__DelegateSignature Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.BndEvt__WBP_Trading_Pal_WBP_PalCommonCharacterSlotButton_Edit_K2Node_ComponentBoundEvent_8_OnUnhoveredButton__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWBP_PalCharacterSlotButtonBase_C*Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::BndEvt__WBP_Trading_Pal_WBP_PalCommonCharacterSlotButton_Edit_K2Node_ComponentBoundEvent_8_OnUnhoveredButton__DelegateSignature(class UWBP_PalCharacterSlotButtonBase_C* Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "BndEvt__WBP_Trading_Pal_WBP_PalCommonCharacterSlotButton_Edit_K2Node_ComponentBoundEvent_8_OnUnhoveredButton__DelegateSignature");

	Params::WBP_Trading_Pal_C_BndEvt__WBP_Trading_Pal_WBP_PalCommonCharacterSlotButton_Edit_K2Node_ComponentBoundEvent_8_OnUnhoveredButton__DelegateSignature Parms{};

	Parms.Widget = Widget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.BndEvt__WBP_Trading_Pal_WBP_PalInGameMenuItemSlotButton_Cost_K2Node_ComponentBoundEvent_9_OnClickedButton__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWBP_PalItemSlotButtonBase_C*     Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// EPalItemSlotPressType                   PressType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::BndEvt__WBP_Trading_Pal_WBP_PalInGameMenuItemSlotButton_Cost_K2Node_ComponentBoundEvent_9_OnClickedButton__DelegateSignature(class UWBP_PalItemSlotButtonBase_C* Widget, EPalItemSlotPressType PressType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "BndEvt__WBP_Trading_Pal_WBP_PalInGameMenuItemSlotButton_Cost_K2Node_ComponentBoundEvent_9_OnClickedButton__DelegateSignature");

	Params::WBP_Trading_Pal_C_BndEvt__WBP_Trading_Pal_WBP_PalInGameMenuItemSlotButton_Cost_K2Node_ComponentBoundEvent_9_OnClickedButton__DelegateSignature Parms{};

	Parms.Widget = Widget;
	Parms.PressType = PressType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.BndEvt__WBP_Trading_Pal_WBP_PalInvisibleButton_Lock_K2Node_ComponentBoundEvent_15_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::BndEvt__WBP_Trading_Pal_WBP_PalInvisibleButton_Lock_K2Node_ComponentBoundEvent_15_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "BndEvt__WBP_Trading_Pal_WBP_PalInvisibleButton_Lock_K2Node_ComponentBoundEvent_15_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_Trading_Pal_C_BndEvt__WBP_Trading_Pal_WBP_PalInvisibleButton_Lock_K2Node_ComponentBoundEvent_15_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.BndEvt__WBP_Trading_Pal_WBP_PalInvisibleButton_Minus_K2Node_ComponentBoundEvent_11_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::BndEvt__WBP_Trading_Pal_WBP_PalInvisibleButton_Minus_K2Node_ComponentBoundEvent_11_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "BndEvt__WBP_Trading_Pal_WBP_PalInvisibleButton_Minus_K2Node_ComponentBoundEvent_11_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_Trading_Pal_C_BndEvt__WBP_Trading_Pal_WBP_PalInvisibleButton_Minus_K2Node_ComponentBoundEvent_11_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.BndEvt__WBP_Trading_Pal_WBP_PalInvisibleButton_Plus_K2Node_ComponentBoundEvent_10_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::BndEvt__WBP_Trading_Pal_WBP_PalInvisibleButton_Plus_K2Node_ComponentBoundEvent_10_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "BndEvt__WBP_Trading_Pal_WBP_PalInvisibleButton_Plus_K2Node_ComponentBoundEvent_10_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_Trading_Pal_C_BndEvt__WBP_Trading_Pal_WBP_PalInvisibleButton_Plus_K2Node_ComponentBoundEvent_10_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.CustomNavigation_ToCancel
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Param_Navigation                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_Trading_Pal_C::CustomNavigation_ToCancel(EUINavigation Param_Navigation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "CustomNavigation_ToCancel");

	Params::WBP_Trading_Pal_C_CustomNavigation_ToCancel Parms{};

	Parms.Param_Navigation = Param_Navigation;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Trading_Pal_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.Enable Pal Select
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    EnableBox                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    EnableParty                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::Enable_Pal_Select(bool EnableBox, bool EnableParty)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "Enable Pal Select");

	Params::WBP_Trading_Pal_C_Enable_Pal_Select Parms{};

	Parms.EnableBox = EnableBox;
	Parms.EnableParty = EnableParty;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.ExecuteUbergraph_WBP_Trading_Pal
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::ExecuteUbergraph_WBP_Trading_Pal(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "ExecuteUbergraph_WBP_Trading_Pal");

	Params::WBP_Trading_Pal_C_ExecuteUbergraph_WBP_Trading_Pal Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.OnCancelAction
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Pal_C::OnCancelAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "OnCancelAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.OnClickedCostSelectSlot
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             StaticItemId                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::OnClickedCostSelectSlot(class FName StaticItemId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "OnClickedCostSelectSlot");

	Params::WBP_Trading_Pal_C_OnClickedCostSelectSlot Parms{};

	Parms.StaticItemId = StaticItemId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.OnClickedRemoveTradeButton
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TradeIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::OnClickedRemoveTradeButton(int32 TradeIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "OnClickedRemoveTradeButton");

	Params::WBP_Trading_Pal_C_OnClickedRemoveTradeButton Parms{};

	Parms.TradeIndex = TradeIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.OnClickSlot
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_PalCharacterSlotButtonBase_C*Param_Slot                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// EPalItemSlotPressType                   PressType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::OnClickSlot(class UWBP_PalCharacterSlotButtonBase_C* Param_Slot, EPalItemSlotPressType PressType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "OnClickSlot");

	Params::WBP_Trading_Pal_C_OnClickSlot Parms{};

	Parms.Param_Slot = Param_Slot;
	Parms.PressType = PressType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.OnHoverPalSlot
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPalIndividualCharacterSlot*      Param_Slot                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::OnHoverPalSlot(class UPalIndividualCharacterSlot* Param_Slot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "OnHoverPalSlot");

	Params::WBP_Trading_Pal_C_OnHoverPalSlot Parms{};

	Parms.Param_Slot = Param_Slot;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.OnHoverPartyPalSlot
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_PalCharacterSlotButtonBase_C*Param_Slot                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::OnHoverPartyPalSlot(class UWBP_PalCharacterSlotButtonBase_C* Param_Slot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "OnHoverPartyPalSlot");

	Params::WBP_Trading_Pal_C_OnHoverPartyPalSlot Parms{};

	Parms.Param_Slot = Param_Slot;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Trading_Pal_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.OnPrivateLockChanged
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGuid                            LockPlayerUId                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::OnPrivateLockChanged(const struct FGuid& LockPlayerUId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "OnPrivateLockChanged");

	Params::WBP_Trading_Pal_C_OnPrivateLockChanged Parms{};

	Parms.LockPlayerUId = std::move(LockPlayerUId);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.OnSetup
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Pal_C::OnSetup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "OnSetup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.OnStoreSlotUpdate
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPalIndividualCharacterSlot*      Param_Slot                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPalIndividualCharacterHandle*    LastHandle                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::OnStoreSlotUpdate(class UPalIndividualCharacterSlot* Param_Slot, class UPalIndividualCharacterHandle* LastHandle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "OnStoreSlotUpdate");

	Params::WBP_Trading_Pal_C_OnStoreSlotUpdate Parms{};

	Parms.Param_Slot = Param_Slot;
	Parms.LastHandle = LastHandle;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.OnTradeEdit
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Param_Index                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::OnTradeEdit(int32 Param_Index)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "OnTradeEdit");

	Params::WBP_Trading_Pal_C_OnTradeEdit Parms{};

	Parms.Param_Index = Param_Index;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.OnTradeHovered
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TradeIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::OnTradeHovered(int32 TradeIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "OnTradeHovered");

	Params::WBP_Trading_Pal_C_OnTradeHovered Parms{};

	Parms.TradeIndex = TradeIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.OnTradeUnhovered
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TradeIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::OnTradeUnhovered(int32 TradeIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "OnTradeUnhovered");

	Params::WBP_Trading_Pal_C_OnTradeUnhovered Parms{};

	Parms.TradeIndex = TradeIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.OnUnhoverPalSlot
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Pal_C::OnUnhoverPalSlot()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "OnUnhoverPalSlot");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.OnUnhoverPartyPalSlot
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_PalCharacterSlotButtonBase_C*Param_Slot                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::OnUnhoverPartyPalSlot(class UWBP_PalCharacterSlotButtonBase_C* Param_Slot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "OnUnhoverPartyPalSlot");

	Params::WBP_Trading_Pal_C_OnUnhoverPartyPalSlot Parms{};

	Parms.Param_Slot = Param_Slot;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.OnViewDetailInput
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Pal_C::OnViewDetailInput()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "OnViewDetailInput");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "PreConstruct");

	Params::WBP_Trading_Pal_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.SetCostSettingNum
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   NewNum                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::SetCostSettingNum(int32 NewNum)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "SetCostSettingNum");

	Params::WBP_Trading_Pal_C_SetCostSettingNum Parms{};

	Parms.NewNum = NewNum;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.Setup
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Pal_C::Setup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "Setup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.Switch Sell Panel
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ToSellList                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Trading_Pal_C::Switch_Sell_Panel(bool ToSellList)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "Switch Sell Panel");

	Params::WBP_Trading_Pal_C_Switch_Sell_Panel Parms{};

	Parms.ToSellList = ToSellList;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.Toggle Private Lock
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Pal_C::Toggle_Private_Lock()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "Toggle Private Lock");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.ToNextFocus
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Pal_C::ToNextFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "ToNextFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.ToPrevFocus
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Pal_C::ToPrevFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "ToPrevFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.ToSellListPanel
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Pal_C::ToSellListPanel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "ToSellListPanel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.ToSetSellPanel
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Pal_C::ToSetSellPanel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "ToSetSellPanel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.Update Sell List
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Pal_C::Update_Sell_List()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "Update Sell List");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.Validate Current Trade Info
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Trading_Pal_C::Validate_Current_Trade_Info()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "Validate Current Trade Info");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Trading_Pal.WBP_Trading_Pal_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_Trading_Pal_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Trading_Pal_C", "BP_GetDesiredFocusTarget");

	Params::WBP_Trading_Pal_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

