#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_IngameMenu_ChestManage_TakeOut

#include "Basic.hpp"

#include "WBP_IngameMenu_ChestManage_TakeOut_classes.hpp"
#include "WBP_IngameMenu_ChestManage_TakeOut_parameters.hpp"


namespace SDK
{

// Function WBP_IngameMenu_ChestManage_TakeOut.WBP_IngameMenu_ChestManage_TakeOut_C.BndEvt__WBP_IngameMenu_ChestManage_TakeOut_WBP_CommonButton_Confirm_K2Node_ComponentBoundEvent_8_OnClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_IngameMenu_ChestManage_TakeOut_C::BndEvt__WBP_IngameMenu_ChestManage_TakeOut_WBP_CommonButton_Confirm_K2Node_ComponentBoundEvent_8_OnClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_TakeOut_C", "BndEvt__WBP_IngameMenu_ChestManage_TakeOut_WBP_CommonButton_Confirm_K2Node_ComponentBoundEvent_8_OnClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameMenu_ChestManage_TakeOut.WBP_IngameMenu_ChestManage_TakeOut_C.BndEvt__WBP_IngameMenu_ChestManage_TakeOut_WBP_Menu_btn_K2Node_ComponentBoundEvent_5_OnButtonClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_IngameMenu_ChestManage_TakeOut_C::BndEvt__WBP_IngameMenu_ChestManage_TakeOut_WBP_Menu_btn_K2Node_ComponentBoundEvent_5_OnButtonClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_TakeOut_C", "BndEvt__WBP_IngameMenu_ChestManage_TakeOut_WBP_Menu_btn_K2Node_ComponentBoundEvent_5_OnButtonClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameMenu_ChestManage_TakeOut.WBP_IngameMenu_ChestManage_TakeOut_C.BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Add10_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// int32                                   Progress                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_ChestManage_TakeOut_C::BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Add10_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature(int32 Progress)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_TakeOut_C", "BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Add10_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature");

	Params::WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Add10_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature Parms{};

	Parms.Progress = Progress;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_ChestManage_TakeOut.WBP_IngameMenu_ChestManage_TakeOut_C.BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_NumArrow_1_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// int32                                   Progress                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_ChestManage_TakeOut_C::BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_NumArrow_1_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature(int32 Progress)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_TakeOut_C", "BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_NumArrow_1_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature");

	Params::WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_NumArrow_1_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature Parms{};

	Parms.Progress = Progress;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_ChestManage_TakeOut.WBP_IngameMenu_ChestManage_TakeOut_C.BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Slider_K2Node_ComponentBoundEvent_7_OnValueChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// int32                                   NewCount                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_ChestManage_TakeOut_C::BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Slider_K2Node_ComponentBoundEvent_7_OnValueChanged__DelegateSignature(int32 NewCount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_TakeOut_C", "BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Slider_K2Node_ComponentBoundEvent_7_OnValueChanged__DelegateSignature");

	Params::WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Slider_K2Node_ComponentBoundEvent_7_OnValueChanged__DelegateSignature Parms{};

	Parms.NewCount = NewCount;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_ChestManage_TakeOut.WBP_IngameMenu_ChestManage_TakeOut_C.BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub10_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// int32                                   Progress                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_ChestManage_TakeOut_C::BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub10_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature(int32 Progress)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_TakeOut_C", "BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub10_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature");

	Params::WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub10_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature Parms{};

	Parms.Progress = Progress;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_ChestManage_TakeOut.WBP_IngameMenu_ChestManage_TakeOut_C.BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// int32                                   Progress                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_ChestManage_TakeOut_C::BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature(int32 Progress)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_TakeOut_C", "BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature");

	Params::WBP_IngameMenu_ChestManage_TakeOut_C_BndEvt__WBP_IngameMenu_WorkSpace_WBP_IngameMenu_WorkSpace_Sub_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature Parms{};

	Parms.Progress = Progress;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_ChestManage_TakeOut.WBP_IngameMenu_ChestManage_TakeOut_C.ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_ChestManage_TakeOut_C::ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_TakeOut_C", "ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut");

	Params::WBP_IngameMenu_ChestManage_TakeOut_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage_TakeOut Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_ChestManage_TakeOut.WBP_IngameMenu_ChestManage_TakeOut_C.OnTakeOutClosed__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UWBP_IngameMenu_ChestManage_TakeOut_C::OnTakeOutClosed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_TakeOut_C", "OnTakeOutClosed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameMenu_ChestManage_TakeOut.WBP_IngameMenu_ChestManage_TakeOut_C.OnTakeOutConfirmed__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPalItemId                       TakeOutId                                              (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// int32                                   TakeOutCount                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_ChestManage_TakeOut_C::OnTakeOutConfirmed__DelegateSignature(const struct FPalItemId& TakeOutId, int32 TakeOutCount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_TakeOut_C", "OnTakeOutConfirmed__DelegateSignature");

	Params::WBP_IngameMenu_ChestManage_TakeOut_C_OnTakeOutConfirmed__DelegateSignature Parms{};

	Parms.TakeOutId = std::move(TakeOutId);
	Parms.TakeOutCount = TakeOutCount;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_ChestManage_TakeOut.WBP_IngameMenu_ChestManage_TakeOut_C.SetMax
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_IngameMenu_ChestManage_TakeOut_C::SetMax()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_TakeOut_C", "SetMax");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameMenu_ChestManage_TakeOut.WBP_IngameMenu_ChestManage_TakeOut_C.Setup
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPalItemAndNum                   ItemAndNum                                             (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_IngameMenu_ChestManage_TakeOut_C::Setup(const struct FPalItemAndNum& ItemAndNum)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_TakeOut_C", "Setup");

	Params::WBP_IngameMenu_ChestManage_TakeOut_C_Setup Parms{};

	Parms.ItemAndNum = std::move(ItemAndNum);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_ChestManage_TakeOut.WBP_IngameMenu_ChestManage_TakeOut_C.UpdateSelectCount
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_IngameMenu_ChestManage_TakeOut_C::UpdateSelectCount()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_TakeOut_C", "UpdateSelectCount");

	UObject::ProcessEvent(Func, nullptr);
}

}

