#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DemoOP_TerminalShadow

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_DemoOP_TerminalShadow.WBP_DemoOP_TerminalShadow_C.ExecuteUbergraph_WBP_DemoOP_TerminalShadow
// 0x0010 (0x0010 - 0x0000)
struct WBP_DemoOP_TerminalShadow_C_ExecuteUbergraph_WBP_DemoOP_TerminalShadow final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_66F0[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_DemoOP_TerminalShadow_C_ExecuteUbergraph_WBP_DemoOP_TerminalShadow) == 0x000008, "Wrong alignment on WBP_DemoOP_TerminalShadow_C_ExecuteUbergraph_WBP_DemoOP_TerminalShadow");
static_assert(sizeof(WBP_DemoOP_TerminalShadow_C_ExecuteUbergraph_WBP_DemoOP_TerminalShadow) == 0x000010, "Wrong size on WBP_DemoOP_TerminalShadow_C_ExecuteUbergraph_WBP_DemoOP_TerminalShadow");
static_assert(offsetof(WBP_DemoOP_TerminalShadow_C_ExecuteUbergraph_WBP_DemoOP_TerminalShadow, EntryPoint) == 0x000000, "Member 'WBP_DemoOP_TerminalShadow_C_ExecuteUbergraph_WBP_DemoOP_TerminalShadow::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_DemoOP_TerminalShadow_C_ExecuteUbergraph_WBP_DemoOP_TerminalShadow, CallFunc_PlayAnimation_ReturnValue) == 0x000008, "Member 'WBP_DemoOP_TerminalShadow_C_ExecuteUbergraph_WBP_DemoOP_TerminalShadow::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");

}

