#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_IngameMenu_ChestManage

#include "Basic.hpp"

#include "WBP_IngameMenu_ChestManage_classes.hpp"
#include "WBP_IngameMenu_ChestManage_parameters.hpp"


namespace SDK
{

// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.BndEvt__WBP_IngameMenu_Chest_WBP_Menu_btn_K2Node_ComponentBoundEvent_7_OnButtonClicked__DelegateSignature
// (BlueprintEvent)

void UWBP_IngameMenu_ChestManage_C::BndEvt__WBP_IngameMenu_Chest_WBP_Menu_btn_K2Node_ComponentBoundEvent_7_OnButtonClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "BndEvt__WBP_IngameMenu_Chest_WBP_Menu_btn_K2Node_ComponentBoundEvent_7_OnButtonClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.BndEvt__WBP_IngameMenu_ChestManage_WBP_Common_Inventory_K2Node_ComponentBoundEvent_0_OnRightClickSlot__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWBP_PalItemSlotButtonBase_C*     Param_Slot                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// EPalItemSlotPressType                   PressType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_ChestManage_C::BndEvt__WBP_IngameMenu_ChestManage_WBP_Common_Inventory_K2Node_ComponentBoundEvent_0_OnRightClickSlot__DelegateSignature(class UWBP_PalItemSlotButtonBase_C* Param_Slot, EPalItemSlotPressType PressType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "BndEvt__WBP_IngameMenu_ChestManage_WBP_Common_Inventory_K2Node_ComponentBoundEvent_0_OnRightClickSlot__DelegateSignature");

	Params::WBP_IngameMenu_ChestManage_C_BndEvt__WBP_IngameMenu_ChestManage_WBP_Common_Inventory_K2Node_ComponentBoundEvent_0_OnRightClickSlot__DelegateSignature Parms{};

	Parms.Param_Slot = Param_Slot;
	Parms.PressType = PressType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.BndEvt__WBP_IngameMenu_ChestManage_WBP_Common_Inventory_K2Node_ComponentBoundEvent_12_OnClickedInventorySortButton__DelegateSignature
// (BlueprintEvent)

void UWBP_IngameMenu_ChestManage_C::BndEvt__WBP_IngameMenu_ChestManage_WBP_Common_Inventory_K2Node_ComponentBoundEvent_12_OnClickedInventorySortButton__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "BndEvt__WBP_IngameMenu_ChestManage_WBP_Common_Inventory_K2Node_ComponentBoundEvent_12_OnClickedInventorySortButton__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.BndEvt__WBP_IngameMenu_ChestManage_WBP_Common_Inventory_K2Node_ComponentBoundEvent_5_OnHoveredInventorySlot__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWBP_PalItemSlotButtonBase_C*     SlotButton                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_ChestManage_C::BndEvt__WBP_IngameMenu_ChestManage_WBP_Common_Inventory_K2Node_ComponentBoundEvent_5_OnHoveredInventorySlot__DelegateSignature(class UWBP_PalItemSlotButtonBase_C* SlotButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "BndEvt__WBP_IngameMenu_ChestManage_WBP_Common_Inventory_K2Node_ComponentBoundEvent_5_OnHoveredInventorySlot__DelegateSignature");

	Params::WBP_IngameMenu_ChestManage_C_BndEvt__WBP_IngameMenu_ChestManage_WBP_Common_Inventory_K2Node_ComponentBoundEvent_5_OnHoveredInventorySlot__DelegateSignature Parms{};

	Parms.SlotButton = SlotButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.BndEvt__WBP_IngameMenu_ChestManage_WBP_IngameMenu_ChestManage_TakeOut_K2Node_ComponentBoundEvent_2_OnTakeOutClosed__DelegateSignature
// (BlueprintEvent)

void UWBP_IngameMenu_ChestManage_C::BndEvt__WBP_IngameMenu_ChestManage_WBP_IngameMenu_ChestManage_TakeOut_K2Node_ComponentBoundEvent_2_OnTakeOutClosed__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "BndEvt__WBP_IngameMenu_ChestManage_WBP_IngameMenu_ChestManage_TakeOut_K2Node_ComponentBoundEvent_2_OnTakeOutClosed__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.BndEvt__WBP_IngameMenu_ChestManage_WBP_IngameMenu_ChestManage_TakeOut_K2Node_ComponentBoundEvent_3_OnTakeOutConfirmed__DelegateSignature
// (BlueprintEvent)
// Parameters:
// struct FPalItemId                       TakeOutId                                              (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// int32                                   TakeOutCount                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_ChestManage_C::BndEvt__WBP_IngameMenu_ChestManage_WBP_IngameMenu_ChestManage_TakeOut_K2Node_ComponentBoundEvent_3_OnTakeOutConfirmed__DelegateSignature(const struct FPalItemId& TakeOutId, int32 TakeOutCount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "BndEvt__WBP_IngameMenu_ChestManage_WBP_IngameMenu_ChestManage_TakeOut_K2Node_ComponentBoundEvent_3_OnTakeOutConfirmed__DelegateSignature");

	Params::WBP_IngameMenu_ChestManage_C_BndEvt__WBP_IngameMenu_ChestManage_WBP_IngameMenu_ChestManage_TakeOut_K2Node_ComponentBoundEvent_3_OnTakeOutConfirmed__DelegateSignature Parms{};

	Parms.TakeOutId = std::move(TakeOutId);
	Parms.TakeOutCount = TakeOutCount;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.BndEvt__WBP_IngameMenu_ChestManage_WBP_IngameMenu_ItemSearchList_K2Node_ComponentBoundEvent_1_OnRightClickSlot__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UWBP_PalItemSlotButtonBase_C*     Param_Slot                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// EPalItemSlotPressType                   PressType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_ChestManage_C::BndEvt__WBP_IngameMenu_ChestManage_WBP_IngameMenu_ItemSearchList_K2Node_ComponentBoundEvent_1_OnRightClickSlot__DelegateSignature(class UWBP_PalItemSlotButtonBase_C* Param_Slot, EPalItemSlotPressType PressType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "BndEvt__WBP_IngameMenu_ChestManage_WBP_IngameMenu_ItemSearchList_K2Node_ComponentBoundEvent_1_OnRightClickSlot__DelegateSignature");

	Params::WBP_IngameMenu_ChestManage_C_BndEvt__WBP_IngameMenu_ChestManage_WBP_IngameMenu_ItemSearchList_K2Node_ComponentBoundEvent_1_OnRightClickSlot__DelegateSignature Parms{};

	Parms.Param_Slot = Param_Slot;
	Parms.PressType = PressType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.BndEvt__WBP_IngameMenu_ChestManage_WBP_IngameMenu_ItemSearchList_K2Node_ComponentBoundEvent_6_OnSlotHovered__DelegateSignature
// (BlueprintEvent)

void UWBP_IngameMenu_ChestManage_C::BndEvt__WBP_IngameMenu_ChestManage_WBP_IngameMenu_ItemSearchList_K2Node_ComponentBoundEvent_6_OnSlotHovered__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "BndEvt__WBP_IngameMenu_ChestManage_WBP_IngameMenu_ItemSearchList_K2Node_ComponentBoundEvent_6_OnSlotHovered__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_IngameMenu_ChestManage_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.CustomNavi_ToCloseButton
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Param_Navigation                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_IngameMenu_ChestManage_C::CustomNavi_ToCloseButton(EUINavigation Param_Navigation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "CustomNavi_ToCloseButton");

	Params::WBP_IngameMenu_ChestManage_C_CustomNavi_ToCloseButton Parms{};

	Parms.Param_Navigation = Param_Navigation;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.CustomNavi_ToInventorySlot
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Param_Navigation                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_IngameMenu_ChestManage_C::CustomNavi_ToInventorySlot(EUINavigation Param_Navigation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "CustomNavi_ToInventorySlot");

	Params::WBP_IngameMenu_ChestManage_C_CustomNavi_ToInventorySlot Parms{};

	Parms.Param_Navigation = Param_Navigation;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_IngameMenu_ChestManage_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.EnableUpdate
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_IngameMenu_ChestManage_C::EnableUpdate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "EnableUpdate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.ExecuteUbergraph_WBP_IngameMenu_ChestManage
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_ChestManage_C::ExecuteUbergraph_WBP_IngameMenu_ChestManage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "ExecuteUbergraph_WBP_IngameMenu_ChestManage");

	Params::WBP_IngameMenu_ChestManage_C_ExecuteUbergraph_WBP_IngameMenu_ChestManage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.GetInventoryLastHoveredFocusTarget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWidget*                          Widget                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_ChestManage_C::GetInventoryLastHoveredFocusTarget(class UWidget** Widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "GetInventoryLastHoveredFocusTarget");

	Params::WBP_IngameMenu_ChestManage_C_GetInventoryLastHoveredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Widget != nullptr)
		*Widget = Parms.Widget;
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.GetInventoryTopFocustTarget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWidget*                          FocusTarget                                            (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_ChestManage_C::GetInventoryTopFocustTarget(class UWidget** FocusTarget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "GetInventoryTopFocustTarget");

	Params::WBP_IngameMenu_ChestManage_C_GetInventoryTopFocustTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FocusTarget != nullptr)
		*FocusTarget = Parms.FocusTarget;
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.InputMethodChanged
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// ECommonInputType                        InputType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_ChestManage_C::InputMethodChanged(ECommonInputType InputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "InputMethodChanged");

	Params::WBP_IngameMenu_ChestManage_C_InputMethodChanged Parms{};

	Parms.InputType = InputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.On Camp Item Stack Info Update
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPalUIBaseCampItemDispenserModel* Model                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_ChestManage_C::On_Camp_Item_Stack_Info_Update(class UPalUIBaseCampItemDispenserModel* Model)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "On Camp Item Stack Info Update");

	Params::WBP_IngameMenu_ChestManage_C_On_Camp_Item_Stack_Info_Update Parms{};

	Parms.Model = Model;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.OnAddedToFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FFocusEvent                      InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_IngameMenu_ChestManage_C::OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "OnAddedToFocusPath");

	Params::WBP_IngameMenu_ChestManage_C_OnAddedToFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.OnCancelAction
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_IngameMenu_ChestManage_C::OnCancelAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "OnCancelAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.OnClickedPreferenceButton__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UWBP_IngameMenu_ChestManage_C::OnClickedPreferenceButton__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "OnClickedPreferenceButton__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.OnClickedQuickMoveButton__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void UWBP_IngameMenu_ChestManage_C::OnClickedQuickMoveButton__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "OnClickedQuickMoveButton__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.OnClose
// (Event, Protected, BlueprintEvent)

void UWBP_IngameMenu_ChestManage_C::OnClose()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "OnClose");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.OnRemovedFromFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FFocusEvent                      InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_IngameMenu_ChestManage_C::OnRemovedFromFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "OnRemovedFromFocusPath");

	Params::WBP_IngameMenu_ChestManage_C_OnRemovedFromFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.OnSetup
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UWBP_IngameMenu_ChestManage_C::OnSetup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "OnSetup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.OnTakeOutClose
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_IngameMenu_ChestManage_C::OnTakeOutClose()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "OnTakeOutClose");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.Refill
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_IngameMenu_ChestManage_C::Refill()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "Refill");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.Reset Focus
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    TryFocusItemList                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_ChestManage_C::Reset_Focus(bool TryFocusItemList)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "Reset Focus");

	Params::WBP_IngameMenu_ChestManage_C_Reset_Focus Parms{};

	Parms.TryFocusItemList = TryFocusItemList;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.Setup
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBP_PalInventoryModel_C*          Param_InventoryModel                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPalUIBaseCampItemDispenserModel* Param_DispenserModel                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_ChestManage_C::Setup(class UBP_PalInventoryModel_C* Param_InventoryModel, class UPalUIBaseCampItemDispenserModel* Param_DispenserModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "Setup");

	Params::WBP_IngameMenu_ChestManage_C_Setup Parms{};

	Parms.Param_InventoryModel = Param_InventoryModel;
	Parms.Param_DispenserModel = Param_DispenserModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.Setup Take Out
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPalItemAndNum                   ItemAndNum                                             (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_IngameMenu_ChestManage_C::Setup_Take_Out(const struct FPalItemAndNum& ItemAndNum)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "Setup Take Out");

	Params::WBP_IngameMenu_ChestManage_C_Setup_Take_Out Parms{};

	Parms.ItemAndNum = std::move(ItemAndNum);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.Unbind
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_IngameMenu_ChestManage_C::Unbind()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "Unbind");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.UpdateInventoryGreyout
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPalItemSlot*                     Param_Slot                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_IngameMenu_ChestManage_C::UpdateInventoryGreyout(class UPalItemSlot* Param_Slot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "UpdateInventoryGreyout");

	Params::WBP_IngameMenu_ChestManage_C_UpdateInventoryGreyout Parms{};

	Parms.Param_Slot = Param_Slot;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.UpdateInventorySlot
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_PalItemSlotButtonBase_C*     Param_Slot                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// TArray<class FName>                     ItemList                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_IngameMenu_ChestManage_C::UpdateInventorySlot(class UWBP_PalItemSlotButtonBase_C* Param_Slot, const TArray<class FName>& ItemList)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "UpdateInventorySlot");

	Params::WBP_IngameMenu_ChestManage_C_UpdateInventorySlot Parms{};

	Parms.Param_Slot = Param_Slot;
	Parms.ItemList = std::move(ItemList);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_IngameMenu_ChestManage.WBP_IngameMenu_ChestManage_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_IngameMenu_ChestManage_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_IngameMenu_ChestManage_C", "BP_GetDesiredFocusTarget");

	Params::WBP_IngameMenu_ChestManage_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

