#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_AttackWarningLoupe

#include "Basic.hpp"

#include "WBP_AttackWarningLoupe_classes.hpp"
#include "WBP_AttackWarningLoupe_parameters.hpp"


namespace SDK
{

// Function WBP_AttackWarningLoupe.WBP_AttackWarningLoupe_C.CalcScreenPosition
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UWBP_AttackWarningLoupe_C::CalcScreenPosition()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AttackWarningLoupe_C", "CalcScreenPosition");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_AttackWarningLoupe.WBP_AttackWarningLoupe_C.GetLoupeWidgetSize
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FVector2D                        Param_WidgetSize                                       (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_AttackWarningLoupe_C::GetLoupeWidgetSize(struct FVector2D* Param_WidgetSize)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AttackWarningLoupe_C", "GetLoupeWidgetSize");

	Params::WBP_AttackWarningLoupe_C_GetLoupeWidgetSize Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_WidgetSize != nullptr)
		*Param_WidgetSize = std::move(Parms.Param_WidgetSize);
}


// Function WBP_AttackWarningLoupe.WBP_AttackWarningLoupe_C.GetTargetWidgetSize
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector2D                        OutVector                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_AttackWarningLoupe_C::GetTargetWidgetSize(struct FVector2D* OutVector)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AttackWarningLoupe_C", "GetTargetWidgetSize");

	Params::WBP_AttackWarningLoupe_C_GetTargetWidgetSize Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutVector != nullptr)
		*OutVector = std::move(Parms.OutVector);
}


// Function WBP_AttackWarningLoupe.WBP_AttackWarningLoupe_C.GetTargetWorldLocation
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector                          OutVector                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_AttackWarningLoupe_C::GetTargetWorldLocation(struct FVector* OutVector)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AttackWarningLoupe_C", "GetTargetWorldLocation");

	Params::WBP_AttackWarningLoupe_C_GetTargetWorldLocation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutVector != nullptr)
		*OutVector = std::move(Parms.OutVector);
}


// Function WBP_AttackWarningLoupe.WBP_AttackWarningLoupe_C.IsEnableLoupe
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UWBP_AttackWarningLoupe_C::IsEnableLoupe()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AttackWarningLoupe_C", "IsEnableLoupe");

	Params::WBP_AttackWarningLoupe_C_IsEnableLoupe Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_AttackWarningLoupe.WBP_AttackWarningLoupe_C.SetFinalWidgetOpacity
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  CalcedOpacity                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_AttackWarningLoupe_C::SetFinalWidgetOpacity(double CalcedOpacity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AttackWarningLoupe_C", "SetFinalWidgetOpacity");

	Params::WBP_AttackWarningLoupe_C_SetFinalWidgetOpacity Parms{};

	Parms.CalcedOpacity = CalcedOpacity;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_AttackWarningLoupe.WBP_AttackWarningLoupe_C.Setup
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector                          Param_TargetLocation                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_AttackWarningLoupe_C::Setup(const struct FVector& Param_TargetLocation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AttackWarningLoupe_C", "Setup");

	Params::WBP_AttackWarningLoupe_C_Setup Parms{};

	Parms.Param_TargetLocation = std::move(Param_TargetLocation);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_AttackWarningLoupe.WBP_AttackWarningLoupe_C.UpdateArrowImageAngle
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  NewAngle                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_AttackWarningLoupe_C::UpdateArrowImageAngle(double NewAngle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AttackWarningLoupe_C", "UpdateArrowImageAngle");

	Params::WBP_AttackWarningLoupe_C_UpdateArrowImageAngle Parms{};

	Parms.NewAngle = NewAngle;

	UObject::ProcessEvent(Func, &Parms);
}

}

